package dev.simplecore.simplix.demo.web.common.code.service;

import dev.simplecore.simplix.demo.web.common.code.dto.CodeItemDTOs.*;
import dev.simplecore.simplix.demo.domain.common.code.entity.CodeItem;

import dev.simplecore.simplix.demo.domain.common.code.repository.CodeItemRepository;

import dev.simplecore.simplix.web.service.SimpliXBaseService;
import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.core.condition.parser.SearchableParamsParser;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import jakarta.persistence.EntityManager;
import java.util.*;

/**
 * This file was auto-generated by SimpliX Generator
 *
 * Generator Version: 0.0.1
 * Generated At: 2025-07-19T00:54:03.879+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */

/**
 * Service class for managing CodeItem entities.
 * Provides business logic for CRUD operations, batch processing, and search functionality for CodeItem entities.

 */
@Service
@Transactional(readOnly = true)
public class CodeItemService extends SimpliXBaseService<CodeItem, String> {
    
    private final ObjectProvider<CodeGroupService> codeGroupServiceProvider;

    /**
     * Constructs a new CodeItemService with required dependencies.
     *
     * @param repository The repository for CodeItem entities
     * @param entityManager JPA EntityManager for database operations
     * @param codeGroupServiceProvider Provider for CodeGroup service
     */
    public CodeItemService(
        CodeItemRepository repository,
        EntityManager entityManager,
        ObjectProvider<CodeGroupService> codeGroupServiceProvider
    ) {
        super(repository, entityManager);
        
        this.codeGroupServiceProvider = codeGroupServiceProvider;
    }

    /**
     * Creates a new CodeItem entity from the provided DTO.
     *
     * @param createDTO DTO containing the data for the new CodeItem
     * @return CodeItemDetailDTO of the created entity
     * @throws RuntimeException if related entities are not found
     */
    @Transactional
    public CodeItemDetailDTO create(CodeItemCreateDTO createDTO) {
        CodeItem entity = new CodeItem();
        modelMapper.map(createDTO, entity);
        return saveAndGetProjection(entity, createDTO.getCodeGroupId());
    }

    /**
     * Updates an existing CodeItem entity with the provided DTO data.
     *
     * @param entity The existing CodeItem entity to update
     * @param updateDto DTO containing the updated data
     * @return CodeItemDetailDTO of the updated entity
     * @throws RuntimeException if related entities are not found
     */
    @Transactional
    public CodeItemDetailDTO update(CodeItem entity, CodeItemUpdateDTO updateDto) {
        modelMapper.map(updateDto, entity);
        entity.setCodeValueI18n(updateDto.getCodeValueI18n() == null ? new HashMap<>() : updateDto.getCodeValueI18n());

        return saveAndGetProjection(entity, updateDto.getCodeGroupId());
    }

    /**
     * Deletes a CodeItem entity by its ID.
     *
     * @param codeItemId The ID of the CodeItem to delete
     */
    @Transactional
    public void delete(String codeItemId) {
        deleteById(codeItemId);
    }

    /**
     * Deletes multiple CodeItem entities by their IDs.
     *
     * @param codeItemIds List of CodeItem IDs to delete
     */
    @Transactional
    public void batchDelete(List<String> codeItemIds) {
        deleteAllByIds(codeItemIds);
    }

    /**
     * Searches for CodeItem entities using provided search parameters.
     *
     * @param params Map of search parameters and their values
     * @return Page of CodeItemListDTO matching the search criteria
     */
    public Page<CodeItemListDTO> search(Map<String, String> params) {
        SearchCondition<CodeItemSearchDTO> searchCondition =
                new SearchableParamsParser<CodeItemSearchDTO>(CodeItemSearchDTO.class).convert(params);
        return findAllWithSearch(searchCondition, CodeItemListDTO.class);
    }

    /**
     * Searches for CodeItem entities using a SearchCondition object.
     *
     * @param searchCondition Search conditions for filtering CodeItem entities
     * @return Page of CodeItemListDTO matching the search criteria
     */
    public Page<CodeItemListDTO> search(SearchCondition<CodeItemSearchDTO> searchCondition) {
        return findAllWithSearch(searchCondition, CodeItemListDTO.class);
    }

    /**
     * Updates multiple CodeItem entities in a single operation.
     *
     * @param updateDtos Set of DTOs containing update data for multiple CodeItems
     * @return List of CodeItemDetailDTO for the updated entities
     * @throws RuntimeException if any related entities are not found
     */
    @Transactional
    public List<CodeItemDetailDTO> multiUpdate(Set<CodeItemUpdateDTO> updateDtos) {
        List<CodeItemDetailDTO> updatedEntities = new ArrayList<>();

        for (CodeItemUpdateDTO updateDto : updateDtos) {
            if (updateDto.getCodeItemId() == null) {
                continue;
            }

            Optional<CodeItem> entityOpt = findById(updateDto.getCodeItemId());
            if (entityOpt.isPresent()) {
                CodeItem entity = entityOpt.get();
                CodeItemDetailDTO updatedEntity = update(entity, updateDto);
                updatedEntities.add(updatedEntity);
            }
        }

        return updatedEntities;
    }

    /**
     * Performs batch updates on multiple CodeItem entities.
     *
     * @param dto DTO containing the batch update data and target IDs
     * @throws RuntimeException if any related entities are not found
     */
    @Transactional
    public void batchUpdate(CodeItemBatchUpdateDTO dto) {
        List<CodeItem> entities = findAllById(dto.getCodeItemIds());

        if (!entities.isEmpty()) {
            entities.forEach(entity -> {
                
                if (dto.getIsActive() != null) {
                    entity.setIsActive(dto.getIsActive());
                }
                
            });

            saveAll(entities);
        }
    }


    /**
     * Updates the order of a CodeItem entity.
     *
     * @param orderUpdateDto DTO containing the ID and new order value
     * @return CodeItemDetailDTO of the updated entity
     * @throws RuntimeException if the entity is not found
     */
    @Transactional
    public CodeItemDetailDTO updateOrder(CodeItemOrderUpdateDTO orderUpdateDto) {
        CodeItem entity = findById(orderUpdateDto.getCodeItemId())
            .orElseThrow(() -> new RuntimeException("CodeItem not found"));
        
        entity.setSortOrder(orderUpdateDto.getSortOrder());
        
        return saveAndGetProjection(entity, entity.getCodeGroup().getCodeGroupId());
    }

    /**
     * Updates the order of multiple CodeItem entities.
     *
     * @param orderUpdateDtos List of DTOs containing the IDs and new order values
     * @return List of CodeItemDetailDTO of the updated entities
     * @throws RuntimeException if any entity is not found
     */
    @Transactional
    public List<CodeItemDetailDTO> updateOrders(List<CodeItemOrderUpdateDTO> orderUpdateDtos) {
        List<CodeItemDetailDTO> updatedEntities = new ArrayList<>();
        
        for (CodeItemOrderUpdateDTO orderUpdateDto : orderUpdateDtos) {
            if (orderUpdateDto.getCodeItemId() == null) {
                continue;
            }
            
            CodeItem entity = findById(orderUpdateDto.getCodeItemId())
                .orElseThrow(() -> new RuntimeException("CodeItem not found with ID: " + orderUpdateDto.getCodeItemId()));
            
            entity.setSortOrder(orderUpdateDto.getSortOrder());
            CodeItemDetailDTO updatedEntity = saveAndGetProjection(entity, entity.getCodeGroup().getCodeGroupId());
            updatedEntities.add(updatedEntity);
        }
        
        return updatedEntities;
    }



    //----------------------------------

    /**
     * Saves a CodeItem entity and returns its projection.
     * Handles the relationships with other entities.
     *
     * @param entity The CodeItem entity to save
     * @param codeGroupId The CodeGroup ID to set
     * @return CodeItemDetailDTO of the saved entity
     * @throws RuntimeException if saving fails or if related entities are not found
     */
    private CodeItemDetailDTO saveAndGetProjection(CodeItem entity, String codeGroupId) {
        
        //----------------------------------
        // Many-to-one relationships
        //----------------------------------
        
        // CodeGroup
        if (codeGroupId != null) {
            CodeGroupService codeGroupService = codeGroupServiceProvider.getIfAvailable();
            if (codeGroupService != null) {
                entity.setCodeGroup(codeGroupService.findById(codeGroupId)
                    .orElseThrow(() -> new RuntimeException("CodeGroup not found")));
            }
        }

        //----------------------------------
        // Many-to-many relationships
        //----------------------------------

        CodeItem savedEntity = saveAndFlush(entity);
        return findById(savedEntity.getId(), CodeItemDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("Failed to retrieve saved entity"));
    }

    //----------------------------------

    /**
     * Checks if the current user has the specified permission for the entity.
     *
     * @param permission The permission to check (e.g., "view", "edit", "delete")
     * @param codeItemId The ID of the entity to check permissions for. Can be null for new entities
     * @param dto The DTO object containing entity data. Used when codeItemId is null
     * @return true if the user has the permission, false otherwise
     * @throws RuntimeException if the entity is not found with the given codeItemId
     */
    @Override
    public boolean hasOwnerPermission(String permission, String codeItemId, Object dto) {
        // TODO must be implemented

        // // Example implementation
        // CodeItem entity = new CodeItem();
        // if (codeItemId != null) {
        //     entity = findById(codeItemId).orElseThrow(() -> new RuntimeException("CodeItem not found"));
        // } else {
        //     modelMapper.map(dto, entity);
        // }

        // Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        // if (Set.of("view", "edit", "delete").contains(permission)) {
        //     return auth.getName().equals(entity.getUsername());
        // }

        throw new UnsupportedOperationException("Unimplemented method 'hasPermission'");
    }
}
