package dev.simplecore.simplix.demo.domain.common.user.repository;

import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccount;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;

import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-04T15:58:41.833+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
@Repository
public interface UserAccountRepository extends SimpliXBaseRepository<UserAccount, String> {

    Optional<UserAccount> findByUsername(String username);

    boolean existsByUsername(String username);
    
    Optional<UserAccount> findByUsernameAndEnabled(String username, Boolean enabled);
} 