package dev.simplecore.simplix.demo.domain.common.user.repository;

import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;
import org.springframework.stereotype.Repository;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:39:17.973+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
@Repository
public interface UserOrganizationRepository extends SimpliXBaseRepository<UserOrganization, String> {
} 