package dev.simplecore.simplix.demo.domain.common.user.repository;

import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccountLog;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccountLog.UserAccountLogId;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;
import org.springframework.stereotype.Repository;

/**
 * This file was auto-generated by SimpliX Generator
 *
 * Generator Version: 0.0.1
 * Generated At: 2025-04-27T19:16:32.131+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 *
 * Note: This entity uses an embedded ID (composite key).
 * When creating query methods, use path notation for accessing embedded ID fields.
 * 
 * For example, with your embedded ID class UserAccountLogId:
 * - findBylogIdUserId(String userId)
 * - findBylogIdLogTime(LocalDateTime logTime)
 * - findBylogIdUserIdAndLogMessage(String userId, String logMessage)
 */

@Repository
public interface UserAccountLogRepository extends SimpliXBaseRepository<UserAccountLog, UserAccountLogId> {
}
