package dev.simplecore.simplix.demo.domain.common.user.repository;

import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthRolePermission;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;

import org.springframework.stereotype.Repository;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-01-26T01:50:26.595Z
 * Generated By: Taehwan Kwag <thkwag@gmail.com>
 */
@Repository
public interface UserPermissionRepository extends SimpliXBaseRepository<AuthRolePermission, String> {
} 