package dev.simplecore.simplix.demo.domain.common.system.repository;

import dev.simplecore.simplix.demo.domain.common.system.entity.CodeItem;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;
import org.springframework.stereotype.Repository;

/**
 * This file was auto-generated by SimpliX Generator
 *
 * Generator Version: 0.0.1
 * Generated At: 2025-07-17T00:33:22.394+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */

@Repository
public interface CodeItemRepository extends SimpliXBaseRepository<CodeItem, String> {
}
