package dev.simplecore.simplix.demo.web.common.user.controller.web;

import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccountLog;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccountLog.UserAccountLogId;
import dev.simplecore.simplix.demo.web.common.user.dto.UserAccountLogDTOs.UserAccountLogDetailDTO;
import dev.simplecore.simplix.demo.web.common.user.service.UserAccountLogService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * This file was auto-generated by SimpliX Generator
 *
 * Generator Version: 0.0.1
 * Generated At: 2025-04-27T19:16:32.131+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */

/**
 * 사용자 계정 변경로그
 *
 */
@Controller
@RequestMapping("/user/accountlog")
public class UserAccountLogController extends SimpliXBaseController<UserAccountLog, UserAccountLogId> {

    private final UserAccountLogService service;

    /**
     * Constructor for UserAccountLogController
     *
     * @param service The service instance for handling UserAccountLog operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    protected UserAccountLogController(UserAccountLogService service) {
        super(service);
        this.service = service;

    }

    /**
     * Displays the list page for UserAccountLog entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    @GetMapping("/list")
    @PreAuthorize("hasPermission('UserAccountLog', 'list')")
    public String list(Model model) {
        model.addAttribute("pageTitle", "사용자 계정 변경로그 관리");
        addSelectData(model);
        return "user/accountlog/list";
    }

    /**
     * Displays the detail page for a UserAccountLog entity
     *
     * @param userId userId
     * @param logTime logTime
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    @GetMapping("/detail/{userId}__{logTime}")
    @PreAuthorize("hasPermission('UserAccountLog', 'view')")
    public String detail(@PathVariable String userId,@PathVariable String logTime, Model model) {
        model.addAttribute("pageTitle", "사용자 계정 변경로그 상세 정보");
        UserAccountLogId id = (new UserAccountLogId()).fromPathVariables(userId, logTime);
        return service.findById(id, UserAccountLogDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "user/accountlog/detail";
            })
            .orElse("redirect:/user/accountlog/list");
    }

    /**
     * Returns the brief content fragment for a UserAccountLog entity
     *
     * @param userId userId
     * @param logTime logTime
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    @GetMapping("/brief/{userId}__{logTime}")
    @PreAuthorize("hasPermission('UserAccountLog', 'view')")
    public String getBrief(@PathVariable String userId,@PathVariable String logTime, Model model) {
        UserAccountLogId id = (new UserAccountLogId()).fromPathVariables(userId, logTime);
        service.findById(id, UserAccountLogDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "user/accountlog/detail :: brief-content";
    }

    /**
     * Displays the edit page for a UserAccountLog entity
     *
     * @param userId userId
     * @param logTime logTime
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    @GetMapping("/edit/{userId}__{logTime}")
    @PreAuthorize("hasPermission('UserAccountLog', 'edit')")
    public String edit(@PathVariable String userId,@PathVariable String logTime, Model model) {
        UserAccountLogId id = (new UserAccountLogId()).fromPathVariables(userId, logTime);
        UserAccountLogDetailDTO item = service.findById(id, UserAccountLogDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("UserAccountLog not found"));

        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "사용자 계정 변경로그 수정");
        addSelectData(model);

        return "user/accountlog/edit";
    }

    /**
     * Displays the create page for a new UserAccountLog entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    @GetMapping("/create")
    @PreAuthorize("hasPermission('UserAccountLog', 'create')")
    public String create(Model model) {
        model.addAttribute("pageTitle", "사용자 계정 변경로그 등록");
        addSelectData(model);

        return "user/accountlog/edit";
    }

    //----------------------------------------------------------

    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-04-27T19:16:32.131+09:00
     */
    private void addSelectData(Model model) {

    }
}
