package dev.simplecore.simplix.demo.web.common.user.controller.web;

import dev.simplecore.simplix.demo.web.common.user.dto.UserOrganizationDTOs.*;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.web.common.user.service.UserOrganizationService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;

import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:39:17.973+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * 사용자 조직
 *
 */
@Controller
@RequestMapping("/user/organization")
public class UserOrganizationController extends SimpliXBaseController<UserOrganization, String> {

    private final UserOrganizationService service;
    /**
     * Constructor for UserOrganizationController
     *
     * @param service The service instance for handling UserOrganization operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    protected UserOrganizationController(UserOrganizationService service) {
        super(service);
        this.service = service;
    }

    /**
     * Displays the list page for UserOrganization entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    @GetMapping("/list")
    @PreAuthorize("hasPermission('UserOrganization', 'list')")
    public String list(Model model) {
        model.addAttribute("pageTitle", "사용자 조직 관리");
        addSelectData(model);
        return "user/organization/list";
    }

    /**
     * Displays the detail page for a UserOrganization entity
     *
     * @param id The ID of the UserOrganization to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    @GetMapping("/detail/{id}")
    @PreAuthorize("hasPermission('UserOrganization', 'view')")
    public String detail(@PathVariable String id, Model model) {
        model.addAttribute("pageTitle", "사용자 조직 상세 정보");
        return service.findById(id, UserOrganizationDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "user/organization/detail";
            })
            .orElse("redirect:/user/organization/list");
    }

    /**
     * Returns the brief content fragment for a UserOrganization entity
     *
     * @param id The ID of the UserOrganization to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    @GetMapping("/brief/{id}")
    @PreAuthorize("hasPermission('UserOrganization', 'view')")
    public String getBrief(@PathVariable String id, Model model) {
        service.findById(id, UserOrganizationDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "user/organization/detail :: brief-content";
    }

    /**
     * Displays the edit page for a UserOrganization entity
     *
     * @param id The ID of the UserOrganization to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    @GetMapping("/edit/{id}")
    @PreAuthorize("hasPermission('UserOrganization', 'edit')")
    public String edit(@PathVariable String id, Model model) {
        UserOrganizationDetailDTO item = service.findById(id, UserOrganizationDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("UserOrganization not found"));
        
        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "사용자 조직 수정");
        addSelectData(model);
        
        return "user/organization/edit";
    }

    /**
     * Displays the create page for a new UserOrganization entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    @GetMapping("/create")
    @PreAuthorize("hasPermission('UserOrganization', 'create')")
    public String create(Model model) {
        model.addAttribute("pageTitle", "사용자 조직 등록");
        addSelectData(model);

        return "user/organization/edit";
    }
    
    //----------------------------------------------------------
    
    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:17.973+09:00
     */
    private void addSelectData(Model model) {
        // Map<String, String> typeMap = Arrays.stream(OrganizationType.values())
        //     .collect(Collectors.toMap(
        //         OrganizationType::name,
        //         OrganizationType::getLabel
        //     ));
        // model.addAttribute("organizationTypeMap", typeMap);
    }
} 