package dev.simplecore.simplix.demo.web.common.user.controller.web;

import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import dev.simplecore.simplix.demo.web.common.user.dto.UserRoleDTOs.UserRoleDetailDTO;
import dev.simplecore.simplix.demo.web.common.user.service.UserRoleService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-06T10:21:42.982+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * 사용자 역할
 *
 */
@Controller
@RequestMapping("/user/role")
public class UserRoleController extends SimpliXBaseController<UserRole, String> {

    private final UserRoleService service;

    /**
     * Constructor for UserRoleController
     *
     * @param service The service instance for handling UserRole operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    protected UserRoleController(UserRoleService service) {
        super(service);
        this.service = service;

    }

    /**
     * Displays the list page for UserRole entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/list")
    @PreAuthorize("hasPermission('UserRole', 'list')")
    public String list(Model model) {
        model.addAttribute("pageTitle", "사용자 역할 관리");
        addSelectData(model);
        return "user/role/list";
    }

    /**
     * Displays the detail page for a UserRole entity
     *
     * @param id The ID of the UserRole to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/detail/{id}")
    @PreAuthorize("hasPermission('UserRole', 'view')")
    public String detail(@PathVariable String id, Model model) {
        model.addAttribute("pageTitle", "사용자 역할 상세 정보");
        return service.findById(id, UserRoleDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "user/role/detail";
            })
            .orElse("redirect:/user/role/list");
    }

    /**
     * Returns the brief content fragment for a UserRole entity
     *
     * @param id The ID of the UserRole to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/brief/{id}")
    @PreAuthorize("hasPermission('UserRole', 'view')")
    public String getBrief(@PathVariable String id, Model model) {
        service.findById(id, UserRoleDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "user/role/detail :: brief-content";
    }

    /**
     * Displays the edit page for a UserRole entity
     *
     * @param id The ID of the UserRole to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/edit/{id}")
    @PreAuthorize("hasPermission('UserRole', 'edit')")
    public String edit(@PathVariable String id, Model model) {
        UserRoleDetailDTO item = service.findById(id, UserRoleDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("UserRole not found"));
        
        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "사용자 역할 수정");
        addSelectData(model);
        
        return "user/role/edit";
    }

    /**
     * Displays the create page for a new UserRole entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/create")
    @PreAuthorize("hasPermission('UserRole', 'create')")
    public String create(Model model) {
        model.addAttribute("pageTitle", "사용자 역할 등록");
        addSelectData(model);

        return "user/role/edit";
    }
    
    //----------------------------------------------------------
    
    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    private void addSelectData(Model model) {

    }
} 