package dev.simplecore.simplix.demo.web.common.user.controller.web;

import dev.simplecore.simplix.demo.web.common.user.dto.UserAccountDTOs.*;
import dev.simplecore.simplix.demo.web.common.user.dto.UserOrganizationDTOs.*;
import dev.simplecore.simplix.demo.web.common.user.dto.UserPositionDTOs.*;
import dev.simplecore.simplix.demo.web.common.user.dto.UserRoleDTOs.*;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccount;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserPosition;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import dev.simplecore.simplix.web.service.SimpliXService;
import dev.simplecore.searchable.core.condition.SearchCondition;

import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;
import dev.simplecore.searchable.core.condition.SearchConditionBuilder;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-04T15:58:41.833+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * 사용자 계정
 *
 */
@Controller
@RequestMapping("/user/account")
public class UserAccountController extends SimpliXBaseController<UserAccount, String> {


    private final SimpliXService<UserPosition, String> userPositionService;
    private final SimpliXService<UserRole, String> userRoleService;
    private final SimpliXService<UserOrganization, String> userOrganizationService;

    /**
     * Constructor for UserAccountController
     *
     * @param service The service instance for handling UserAccount operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    protected UserAccountController(
            SimpliXService<UserAccount, String> service,
            SimpliXService<UserPosition, String> userPositionService,
            SimpliXService<UserRole, String> userRoleService,
            SimpliXService<UserOrganization, String> userOrganizationService) {
        super(service);

        this.userPositionService = userPositionService;
        this.userRoleService = userRoleService;
        this.userOrganizationService = userOrganizationService;
    }

    /**
     * Displays the list page for UserAccount entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    @GetMapping("/list")
    @PreAuthorize("hasPermission('UserAccount', 'list')")
    public String list(Model model) {
        model.addAttribute("pageTitle", "사용자 계정 관리");
        addSelectData(model);
        return "user/account/list";
    }

    /**
     * Displays the detail page for a UserAccount entity
     *
     * @param id The ID of the UserAccount to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    @GetMapping("/detail/{id}")
    @PreAuthorize("hasPermission('UserAccount', 'view')")
    public String detail(@PathVariable String id, Model model) {
        model.addAttribute("pageTitle", "사용자 계정 상세 정보");
        return service.findById(id, UserAccountDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "user/account/detail";
            })
            .orElse("redirect:/user/account/list");
    }

    /**
     * Returns the brief content fragment for a UserAccount entity
     *
     * @param id The ID of the UserAccount to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    @GetMapping("/brief/{id}")
    @PreAuthorize("hasPermission('UserAccount', 'view')")
    public String getBrief(@PathVariable String id, Model model) {
        service.findById(id, UserAccountDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "user/account/detail :: brief-content";
    }

    /**
     * Displays the edit page for a UserAccount entity
     *
     * @param id The ID of the UserAccount to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    @GetMapping("/edit/{id}")
    @PreAuthorize("hasPermission('UserAccount', 'edit')")
    public String edit(@PathVariable String id, Model model) {
        UserAccountDetailDTO item = service.findById(id, UserAccountDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("UserAccount not found"));
        
        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "사용자 계정 수정");
        addSelectData(model);
        
        return "user/account/edit";
    }

    /**
     * Displays the create page for a new UserAccount entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    @GetMapping("/create")
    @PreAuthorize("hasPermission('UserAccount', 'create')")
    public String create(Model model) {
        model.addAttribute("pageTitle", "사용자 계정 등록");
        addSelectData(model);

        return "user/account/edit";
    }
    
    //----------------------------------------------------------
    
    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-04T15:58:41.833+09:00
     */
    private void addSelectData(Model model) {

        SearchCondition<UserPositionSearchDTO> userPositionCondition = SearchConditionBuilder
            .create(UserPositionSearchDTO.class)
            .build();
        model.addAttribute(
            "position",
            userPositionService.findAllWithSearch(userPositionCondition).getContent()
        );

        SearchCondition<UserRoleSearchDTO> userRoleCondition = SearchConditionBuilder
            .create(UserRoleSearchDTO.class)
            .build();
        model.addAttribute(
            "roles",
            userRoleService.findAllWithSearch(userRoleCondition).getContent()
        );

        SearchCondition<UserOrganizationSearchDTO> userOrganizationCondition = SearchConditionBuilder
            .create(UserOrganizationSearchDTO.class)
            .build();
        model.addAttribute(
            "organizations",
            userOrganizationService.findAllWithSearch(userOrganizationCondition).getContent()
        );

    }
} 