package dev.simplecore.simplix.demo.web.common.user.controller.web;

import dev.simplecore.simplix.demo.web.common.user.dto.UserPositionDTOs.*;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserPosition;
import dev.simplecore.simplix.demo.web.common.user.service.UserPositionService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;

import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:39:03.028+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * 사용자 직급
 *
 */
@Controller
@RequestMapping("/user/position")
public class UserPositionController extends SimpliXBaseController<UserPosition, String> {

    private final UserPositionService service;

    /**
     * Constructor for UserPositionController
     *
     * @param service The service instance for handling UserPosition operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    protected UserPositionController(UserPositionService service) {
        super(service);
        this.service = service;

    }

    /**
     * Displays the list page for UserPosition entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    @GetMapping("/list")
    @PreAuthorize("hasPermission('UserPosition', 'list')")
    public String list(Model model) {
        model.addAttribute("pageTitle", "사용자 직급 관리");
        addSelectData(model);
        return "user/position/list";
    }

    /**
     * Displays the detail page for a UserPosition entity
     *
     * @param id The ID of the UserPosition to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    @GetMapping("/detail/{id}")
    @PreAuthorize("hasPermission('UserPosition', 'view')")
    public String detail(@PathVariable String id, Model model) {
        model.addAttribute("pageTitle", "사용자 직급 상세 정보");
        return service.findById(id, UserPositionDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "user/position/detail";
            })
            .orElse("redirect:/user/position/list");
    }

    /**
     * Returns the brief content fragment for a UserPosition entity
     *
     * @param id The ID of the UserPosition to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    @GetMapping("/brief/{id}")
    @PreAuthorize("hasPermission('UserPosition', 'view')")
    public String getBrief(@PathVariable String id, Model model) {
        service.findById(id, UserPositionDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "user/position/detail :: brief-content";
    }

    /**
     * Displays the edit page for a UserPosition entity
     *
     * @param id The ID of the UserPosition to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    @GetMapping("/edit/{id}")
    @PreAuthorize("hasPermission('UserPosition', 'edit')")
    public String edit(@PathVariable String id, Model model) {
        UserPositionDetailDTO item = service.findById(id, UserPositionDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("UserPosition not found"));
        
        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "사용자 직급 수정");
        addSelectData(model);
        
        return "user/position/edit";
    }

    /**
     * Displays the create page for a new UserPosition entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    @GetMapping("/create")
    @PreAuthorize("hasPermission('UserPosition', 'create')")
    public String create(Model model) {
        model.addAttribute("pageTitle", "사용자 직급 등록");
        addSelectData(model);

        return "user/position/edit";
    }
    
    //----------------------------------------------------------
    
    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:39:03.028+09:00
     */
    private void addSelectData(Model model) {

    }
} 