package dev.simplecore.simplix.demo.web.common.system.dto;

import dev.simplecore.simplix.demo.domain.common.system.entity.CodeItem;
import java.util.*;
import java.time.*;
import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.*;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-07-17T00:33:22.394+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */
public class CodeItemDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class CodeItemSearchDTO {
        
        @Schema(description = "Code ID")
        @SearchableField(operators = {EQUALS})
        private String codeId;

        @Schema(description = "Code Key")
        @SearchableField(operators = {EQUALS}, sortable = true)
        private String codeKey;
            
        @Schema(description = "Code Value")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String codeValue;
            
        @Schema(description = "Description")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String description;

        @Schema(description = "Sort Order")
        @SearchableField(sortable = true)
        private Integer sortOrder;

        @Schema(description = "Is Active")
        @SearchableField(operators = {EQUALS})
        private Boolean isActive;
            
        @Schema(description = "Is Default")
        @SearchableField(operators = {EQUALS})
        private Boolean isDefault;
            
        @Schema(description = "Parent ID")
        @SearchableField(operators = {EQUALS})
        private String parentId;

        //----------

        @Schema(description = "Created by")
        private String createdBy;

        @Schema(description = "Created at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated by")
        private String updatedBy;

        @Schema(description = "Updated at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class CodeItemCreateDTO {

        @Schema(description = "Code Key")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 50, message = "{validation.range.length}")
        @Pattern(regexp = "^[A-Z0-9_]+$", message = "{validation.codeKey.pattern}")
        private String codeKey;

        @Schema(description = "Code Value")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 100, message = "{validation.range.length}")
        private String codeValue;

        @Schema(description = "Description")
        @NotBlank(message = "{validation.required}")
        @Length(max = 500, message = "{validation.max.length}")
        private String description;

        @Schema(description = "Sort Order")
        @Min(value = 0, message = "{validation.min.value}")
        @Max(value = 9999, message = "{validation.max.value}")
        private Integer sortOrder;

        @Schema(description = "Is Active")
        @NotNull(message = "{validation.required}")
        private Boolean isActive;

        @Schema(description = "Is Default")
        @NotNull(message = "{validation.required}")
        private Boolean isDefault;

        @Schema(description = "Parent ID")
        @Length(max = 50, message = "{validation.max.length}")
        private String parentId;
        
    }

    @Data
    public static class CodeItemUpdateDTO {
        
        @Schema(description = "Code ID")
        @NotBlank(message = "{validation.required}")
        private String codeId;

        @Schema(description = "Code Key")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 50, message = "{validation.range.length}")
        @Pattern(regexp = "^[A-Z0-9_]+$", message = "{validation.codeKey.pattern}")
        private String codeKey;

        @Schema(description = "Code Value")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 100, message = "{validation.range.length}")
        private String codeValue;

        @Schema(description = "Description")
        @NotBlank(message = "{validation.required}")
        @Length(max = 500, message = "{validation.max.length}")
        private String description;

        @Schema(description = "Sort Order")
        @Min(value = 0, message = "{validation.min.value}")
        @Max(value = 9999, message = "{validation.max.value}")
        private Integer sortOrder;

        @Schema(description = "Is Active")
        @NotNull(message = "{validation.required}")
        private Boolean isActive;

        @Schema(description = "Is Default")
        @NotNull(message = "{validation.required}")
        private Boolean isDefault;

        @Schema(description = "Parent ID")
        @Length(max = 50, message = "{validation.max.length}")
        private String parentId;
    }

    @Data
    public static class CodeItemBatchUpdateDTO {

        @Schema(description = "Code ID list")
        @NotEmpty(message = "{validation.required}")
        @Size(min = 1, max = 100, message = "{validation.range.size}")
        private Set<String> codeIds;

        @Schema(description = "Is Active")
        private Boolean isActive;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class CodeItemDetailDTO {
        
        @Schema(description = "Code ID")
        private String codeId;
        
        @Schema(description = "Code Key")
        private String codeKey;
        
        @Schema(description = "Code Value")
        private String codeValue;
        
        @Schema(description = "Description")
        private String description;
        
        @Schema(description = "Sort Order")
        private Integer sortOrder;
        
        @Schema(description = "Is Active")
        private Boolean isActive;
        
        @Schema(description = "Is Default")
        private Boolean isDefault;
        
        @Schema(description = "Parent ID")
        private String parentId;
        
        @Schema(description = "Children")
        private List<CodeItem> children;

        //----------

        @Schema(description = "Created by")
        private String createdBy;

        @Schema(description = "Created at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated by")
        private String updatedBy;

        @Schema(description = "Updated at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class CodeItemListDTO {
        
        @Schema(description = "Code ID")
        private String codeId;
        
        @Schema(description = "Code Key")
        private String codeKey;
        
        @Schema(description = "Code Value")
        private String codeValue;
        
        @Schema(description = "Description")
        private String description;
        
        @Schema(description = "Sort Order")
        private Integer sortOrder;
        
        @Schema(description = "Is Active")
        private Boolean isActive;
        
        @Schema(description = "Is Default")
        private Boolean isDefault;
        
        @Schema(description = "Parent ID")
        private String parentId;

        @Schema(description = "Children")
        private List<CodeItem> children;

        //----------
        
        @Schema(description = "Created by")
        private String createdBy;

        @Schema(description = "Created at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated by")
        private String updatedBy;

        @Schema(description = "Updated at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }
} 