package dev.simplecore.simplix.demo.domain.common.auth.repository;

import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthRolePermission;
import dev.simplecore.simplix.demo.domain.common.auth.enums.PermissionTargetType;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T18:46:02.603+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
@Repository
public interface AuthRolePermissionRepository extends SimpliXBaseRepository<AuthRolePermission, String> {
    
    @Query("SELECT p FROM AuthRolePermission p " +
           "JOIN p.permission perm " +
           "WHERE perm.name = :permissionName " +
           "AND (" +
           "    (p.targetType = :roleType AND p.role.id IN :roleIds) OR " +
           "    (p.targetType = :orgType AND p.organization.id IN :organizationIds) OR " +
           "    (p.targetType = :userType AND p.userAccount.id = :userId)" +
           ") " +
           "AND (" +
           "    (:actionType = 'list' AND perm.useList = true AND p.listPermission = true) OR " +
           "    (:actionType = 'view' AND perm.useView = true AND p.viewPermission = true) OR " +
           "    (:actionType = 'create' AND perm.useCreate = true AND p.createPermission = true) OR " +
           "    (:actionType = 'edit' AND perm.useEdit = true AND p.editPermission = true) OR " +
           "    (:actionType = 'delete' AND perm.useDelete = true AND p.deletePermission = true) OR " +
           "    (:actionType = 'extra1' AND perm.useExtra1 = true AND p.extra1Permission = true) OR " +
           "    (:actionType = 'extra2' AND perm.useExtra2 = true AND p.extra2Permission = true) OR " +
           "    (:actionType = 'extra3' AND perm.useExtra3 = true AND p.extra3Permission = true) OR " +
           "    (:actionType = 'extra4' AND perm.useExtra4 = true AND p.extra4Permission = true) OR " +
           "    (:actionType = 'extra5' AND perm.useExtra5 = true AND p.extra5Permission = true)" +
           ")")
    List<AuthRolePermission> findPermissions(
        @Param("permissionName") String permissionName,
        @Param("actionType") String actionType,
        @Param("roleIds") List<String> roleIds,
        @Param("organizationIds") List<String> organizationIds,
        @Param("userId") String userId,
        @Param("roleType") PermissionTargetType roleType,
        @Param("orgType") PermissionTargetType orgType,
        @Param("userType") PermissionTargetType userType
    );
} 