package dev.simplecore.simplix.demo.domain.common.auth.repository;

import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthPermission;
import dev.simplecore.simplix.web.repository.SimpliXBaseRepository;

import org.springframework.stereotype.Repository;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:04:09.015+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
@Repository
public interface AuthPermissionRepository extends SimpliXBaseRepository<AuthPermission, String> {
} 