package dev.simplecore.simplix.demo.web.common.system.controller.web;

import dev.simplecore.simplix.demo.domain.common.system.entity.CodeItem;
import dev.simplecore.simplix.demo.web.common.system.service.CodeItemService;
import dev.simplecore.simplix.demo.web.common.system.dto.CodeItemDTOs.*;

import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.core.condition.SearchConditionBuilder;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;

/**
 * This file was auto-generated by SimpliX Generator
 *
 * Generator Version: 0.0.1
 * Generated At: 2025-07-17T00:33:22.394+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */

/**
 * Code Item
 *
 */
@Controller
@RequestMapping("/code/item")
public class CodeItemController extends SimpliXBaseController<CodeItem, String> {

    private final CodeItemService service;

    private final CodeItemService codeItemService;

    /**
     * Constructor for CodeItemController
     *
     * @param service The service instance for handling CodeItem operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    protected CodeItemController(CodeItemService service,
            CodeItemService codeItemService) {
        super(service);
        this.service = service;

        this.codeItemService = codeItemService;
    }

    /**
     * Displays the list page for CodeItem entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    @GetMapping("/list")
    @PreAuthorize("hasPermission('CodeItem', 'list')")
    public String list(Model model) {
        model.addAttribute("pageTitle", "Code Item 관리");
        addSelectData(model);
        return "code/item/list";
    }

    /**
     * Displays the detail page for a CodeItem entity
     *
     * @param codeId The ID of the CodeItem to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    @GetMapping("/detail/{codeId}")
    @PreAuthorize("hasPermission('CodeItem', 'view')")
    public String detail(@PathVariable String codeId, Model model) {
        model.addAttribute("pageTitle", "Code Item 상세 정보");
        
        return service.findById(codeId, CodeItemDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "code/item/detail";
            })
            .orElse("redirect:/code/item/list");
    }

    /**
     * Returns the brief content fragment for a CodeItem entity
     *
     * @param codeId The ID of the CodeItem to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    @GetMapping("/brief/{codeId}")
    @PreAuthorize("hasPermission('CodeItem', 'view')")
    public String getBrief(@PathVariable String codeId, Model model) {
        
        service.findById(codeId, CodeItemDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "code/item/detail :: brief-content";
    }

    /**
     * Displays the edit page for a CodeItem entity
     *
     * @param codeId The ID of the CodeItem to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    @GetMapping("/edit/{codeId}")
    @PreAuthorize("hasPermission('CodeItem', 'edit')")
    public String edit(@PathVariable String codeId, Model model) {
        
        CodeItemDetailDTO item = service.findById(codeId, CodeItemDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("CodeItem not found"));

        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "Code Item 수정");
        addSelectData(model);

        return "code/item/edit";
    }

    /**
     * Displays the create page for a new CodeItem entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    @GetMapping("/create")
    @PreAuthorize("hasPermission('CodeItem', 'create')")
    public String create(Model model) {
        model.addAttribute("pageTitle", "Code Item 등록");
        addSelectData(model);

        return "code/item/edit";
    }

    //----------------------------------------------------------

    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-17T00:33:22.394+09:00
     */
    private void addSelectData(Model model) {

        SearchCondition<CodeItemSearchDTO> codeItemCondition = SearchConditionBuilder
            .create(CodeItemSearchDTO.class)
            .build();
        model.addAttribute(
            "codeItems",
            codeItemService.findAllWithSearch(codeItemCondition).getContent()
        );

    }
}
