package dev.simplecore.simplix.demo.web.common.auth.service;

import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.core.condition.parser.SearchableParamsParser;
import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthPermission;
import dev.simplecore.simplix.demo.domain.common.auth.repository.AuthPermissionRepository;
import dev.simplecore.simplix.demo.web.common.auth.dto.AuthPermissionDTOs.*;
import dev.simplecore.simplix.web.service.SimpliXBaseService;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import jakarta.persistence.EntityManager;
import java.util.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:04:09.015+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * Service class for managing AuthPermission entities.
 * Provides business logic for CRUD operations, batch processing, and search functionality for AuthPermission entities.
 */
@Service
@Transactional
public class AuthPermissionService extends SimpliXBaseService<AuthPermission, String> {
    
    
    /**
     * Constructs a new AuthPermissionService with required dependencies.
     *
     * @param repository The repository for AuthPermission entities
     * @param entityManager JPA EntityManager for database operations
     */
    public AuthPermissionService(
        AuthPermissionRepository repository,
        EntityManager entityManager
    ) {
        super(repository, entityManager);
        
    }

    /**
     * Creates a new AuthPermission entity from the provided DTO.
     *
     * @param createDTO DTO containing the data for the new AuthPermission
     * @return AuthPermissionDetailDTO of the created entity
     * @throws RuntimeException if related entities are not found
     */
    @Transactional
    public AuthPermissionDetailDTO create(AuthPermissionUpdateDTO createDTO) {
        AuthPermission entity = new AuthPermission();
        modelMapper.map(createDTO, entity);
        return saveAndGetProjection(entity, createDTO);
    }

    /**
     * Updates an existing AuthPermission entity with the provided DTO data.
     *
     * @param entity The existing AuthPermission entity to update
     * @param updateDto DTO containing the updated data
     * @return AuthPermissionDetailDTO of the updated entity
     * @throws RuntimeException if related entities are not found
     */
    @Transactional
    public AuthPermissionDetailDTO update(AuthPermission entity, AuthPermissionUpdateDTO updateDto) {
        modelMapper.map(updateDto, entity);
        return saveAndGetProjection(entity, updateDto);
    }

    /**
     * Deletes a AuthPermission entity by its ID.
     *
     * @param id The ID of the AuthPermission to delete
     */
    @Transactional
    public void delete(String id) {
        deleteById(id);
    }

    /**
     * Deletes multiple AuthPermission entities by their IDs.
     *
     * @param ids List of AuthPermission IDs to delete
     */
    @Transactional
    public void batchDelete(List<String> ids) {
        deleteAllByIds(ids);
    }

    /**
     * Searches for AuthPermission entities using provided search parameters.
     *
     * @param params Map of search parameters and their values
     * @return Page of AuthPermissionListDTO matching the search criteria
     */
    public Page<AuthPermissionListDTO> search(Map<String, String> params) {
        SearchCondition<AuthPermissionSearchDTO> searchCondition =
                new SearchableParamsParser<AuthPermissionSearchDTO>(AuthPermissionSearchDTO.class).convert(params);
        return findAllWithSearch(searchCondition, AuthPermissionListDTO.class);
    }

    /**
     * Searches for AuthPermission entities using a SearchCondition object.
     *
     * @param searchCondition Search conditions for filtering AuthPermission entities
     * @return Page of AuthPermissionListDTO matching the search criteria
     */
    public Page<AuthPermissionListDTO> search(SearchCondition<AuthPermissionSearchDTO> searchCondition) {
        return findAllWithSearch(searchCondition, AuthPermissionListDTO.class);
    }

    /**
     * Updates multiple AuthPermission entities in a single operation.
     *
     * @param updateDtos Set of DTOs containing update data for multiple AuthPermissions
     * @return List of AuthPermissionDetailDTO for the updated entities
     * @throws RuntimeException if any related entities are not found
     */
    @Transactional
    public List<AuthPermissionDetailDTO> multiUpdate(Set<AuthPermissionUpdateDTO> updateDtos) {
        List<AuthPermissionDetailDTO> updatedEntities = new ArrayList<>();
        
        for (AuthPermissionUpdateDTO updateDto : updateDtos) {
            if (updateDto.getId() == null) {
                continue;
            }

            Optional<AuthPermission> entityOpt = findById(updateDto.getId());
            if (entityOpt.isPresent()) {
                AuthPermission entity = entityOpt.get();
                AuthPermissionDetailDTO updatedEntity = update(entity, updateDto);
                updatedEntities.add(updatedEntity);
            }
        }
        
        return updatedEntities;
    }

    /**
     * Performs batch updates on multiple AuthPermission entities.
     *
     * @param dto DTO containing the batch update data and target IDs
     * @throws RuntimeException if any related entities are not found
     */
    @Transactional
    public void batchUpdate(AuthPermissionBatchUpdateDTO dto) {
        List<AuthPermission> entities = findAllById(dto.getIds());
        
        entities.forEach(entity -> {
            
            if (dto.getUseList() != null) {
                entity.setUseList(dto.getUseList());
            }
            
            if (dto.getUseView() != null) {
                entity.setUseView(dto.getUseView());
            }
            
            if (dto.getUseCreate() != null) {
                entity.setUseCreate(dto.getUseCreate());
            }
            
            if (dto.getUseEdit() != null) {
                entity.setUseEdit(dto.getUseEdit());
            }
            
            if (dto.getUseDelete() != null) {
                entity.setUseDelete(dto.getUseDelete());
            }
            
            if (dto.getUseExtra1() != null) {
                entity.setUseExtra1(dto.getUseExtra1());
            }
            
            if (dto.getUseExtra2() != null) {
                entity.setUseExtra2(dto.getUseExtra2());
            }
            
            if (dto.getUseExtra3() != null) {
                entity.setUseExtra3(dto.getUseExtra3());
            }
            
            if (dto.getUseExtra4() != null) {
                entity.setUseExtra4(dto.getUseExtra4());
            }
            
            if (dto.getUseExtra5() != null) {
                entity.setUseExtra5(dto.getUseExtra5());
            }
            
            if (dto.getExtra1Name() != null) {
                entity.setExtra1Name(dto.getExtra1Name());
            }
            
            if (dto.getExtra2Name() != null) {
                entity.setExtra2Name(dto.getExtra2Name());
            }
            
            if (dto.getExtra3Name() != null) {
                entity.setExtra3Name(dto.getExtra3Name());
            }
            
            if (dto.getExtra4Name() != null) {
                entity.setExtra4Name(dto.getExtra4Name());
            }
            
            if (dto.getExtra5Name() != null) {
                entity.setExtra5Name(dto.getExtra5Name());
            }
            
        });
        
        saveAll(entities);
    }

    //----------------------------------

    /**
     * Saves a AuthPermission entity and returns its projection.
     * Handles the relationships with other entities.
     *
     * @param entity The AuthPermission entity to save
     * @param dto The DTO containing relationship data
     * @return AuthPermissionDetailDTO of the saved entity
     * @throws RuntimeException if saving fails or if related entities are not found
     */
    private AuthPermissionDetailDTO saveAndGetProjection(AuthPermission entity, AuthPermissionUpdateDTO dto) {
        

        AuthPermission savedEntity = saveAndFlush(entity);
        return findById(savedEntity.getId(), AuthPermissionDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("Failed to retrieve saved entity"));
    }

    //----------------------------------
    
    /**
     * Checks if the current user has the specified permission for the entity.
     * 
     * @param permission The permission to check (e.g., "view", "edit", "delete")
     * @param id The ID of the entity to check permissions for. Can be null for new entities
     * @param dto The DTO object containing entity data. Used when id is null
     * @return true if the user has the permission, false otherwise
     * @throws RuntimeException if the entity is not found with the given id
     */
    @Override
    public boolean hasOwnerPermission(String permission, String id, Object dto) {
        // TODO must be implemented

        // // Example implementation
        // AuthPermission entity = new AuthPermission();
        // if (id != null) {
        //     entity = findById(id).orElseThrow(() -> new RuntimeException("AuthPermission not found"));
        // } else {
        //     modelMapper.map(dto, entity);
        // }

        // Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        // if (Set.of("view", "edit", "delete").contains(permission)) {
        //     return auth.getName().equals(entity.getUsername());
        // }

        throw new UnsupportedOperationException("Unimplemented method 'hasPermission'");
    }
} 