package dev.simplecore.simplix.demo.web.common.auth.service;

import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.core.condition.parser.SearchableParamsParser;
import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthRolePermission;
import dev.simplecore.simplix.demo.domain.common.auth.repository.AuthRolePermissionRepository;
import dev.simplecore.simplix.demo.web.common.auth.dto.AuthRolePermissionDTOs.*;
import dev.simplecore.simplix.demo.web.common.user.service.UserAccountService;
import dev.simplecore.simplix.demo.web.common.user.service.UserOrganizationService;
import dev.simplecore.simplix.demo.web.common.user.service.UserRoleService;
import dev.simplecore.simplix.web.service.SimpliXBaseService;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import jakarta.persistence.EntityManager;
import java.util.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T18:46:02.603+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * Service class for managing AuthRolePermission entities.
 * Provides business logic for CRUD operations, batch processing, and search functionality for AuthRolePermission entities.
 */
@Service
@Transactional
public class AuthRolePermissionService extends SimpliXBaseService<AuthRolePermission, String> {
    
    private final ObjectProvider<AuthPermissionService> authPermissionServiceProvider;
    
    private final ObjectProvider<UserRoleService> userRoleServiceProvider;
    
    private final ObjectProvider<UserOrganizationService> userOrganizationServiceProvider;
    
    private final ObjectProvider<UserAccountService> userAccountServiceProvider;
    
    
    /**
     * Constructs a new AuthRolePermissionService with required dependencies.
     *
     * @param repository The repository for AuthRolePermission entities
     * @param entityManager JPA EntityManager for database operations
     * @param authPermissionServiceProvider Provider for AuthPermission service
     * @param userRoleServiceProvider Provider for UserRole service
     * @param userOrganizationServiceProvider Provider for UserOrganization service
     * @param userAccountServiceProvider Provider for UserAccount service
     */
    public AuthRolePermissionService(
        AuthRolePermissionRepository repository,
        EntityManager entityManager,
        ObjectProvider<AuthPermissionService> authPermissionServiceProvider,
        ObjectProvider<UserRoleService> userRoleServiceProvider,
        ObjectProvider<UserOrganizationService> userOrganizationServiceProvider,
        ObjectProvider<UserAccountService> userAccountServiceProvider
    ) {
        super(repository, entityManager);
        
        this.authPermissionServiceProvider = authPermissionServiceProvider;
        this.userRoleServiceProvider = userRoleServiceProvider;
        this.userOrganizationServiceProvider = userOrganizationServiceProvider;
        this.userAccountServiceProvider = userAccountServiceProvider;
    }

    /**
     * Creates a new AuthRolePermission entity from the provided DTO.
     *
     * @param createDTO DTO containing the data for the new AuthRolePermission
     * @return AuthRolePermissionDetailDTO of the created entity
     * @throws RuntimeException if related entities are not found
     */
    @Transactional
    public AuthRolePermissionDetailDTO create(AuthRolePermissionUpdateDTO createDTO) {
        AuthRolePermission entity = new AuthRolePermission();
        modelMapper.map(createDTO, entity);
        return saveAndGetProjection(entity, createDTO);
    }

    /**
     * Updates an existing AuthRolePermission entity with the provided DTO data.
     *
     * @param entity The existing AuthRolePermission entity to update
     * @param updateDto DTO containing the updated data
     * @return AuthRolePermissionDetailDTO of the updated entity
     * @throws RuntimeException if related entities are not found
     */
    @Transactional
    public AuthRolePermissionDetailDTO update(AuthRolePermission entity, AuthRolePermissionUpdateDTO updateDto) {
        modelMapper.map(updateDto, entity);
        return saveAndGetProjection(entity, updateDto);
    }

    /**
     * Deletes a AuthRolePermission entity by its ID.
     *
     * @param id The ID of the AuthRolePermission to delete
     */
    @Transactional
    public void delete(String id) {
        deleteById(id);
    }

    /**
     * Deletes multiple AuthRolePermission entities by their IDs.
     *
     * @param ids List of AuthRolePermission IDs to delete
     */
    @Transactional
    public void batchDelete(List<String> ids) {
        deleteAllByIds(ids);
    }

    /**
     * Searches for AuthRolePermission entities using provided search parameters.
     *
     * @param params Map of search parameters and their values
     * @return Page of AuthRolePermissionListDTO matching the search criteria
     */
    public Page<AuthRolePermissionListDTO> search(Map<String, String> params) {
        SearchCondition<AuthRolePermissionSearchDTO> searchCondition =
                new SearchableParamsParser<AuthRolePermissionSearchDTO>(AuthRolePermissionSearchDTO.class).convert(params);
        return findAllWithSearch(searchCondition, AuthRolePermissionListDTO.class);
    }

    /**
     * Searches for AuthRolePermission entities using a SearchCondition object.
     *
     * @param searchCondition Search conditions for filtering AuthRolePermission entities
     * @return Page of AuthRolePermissionListDTO matching the search criteria
     */
    public Page<AuthRolePermissionListDTO> search(SearchCondition<AuthRolePermissionSearchDTO> searchCondition) {
        return findAllWithSearch(searchCondition, AuthRolePermissionListDTO.class);
    }

    /**
     * Updates multiple AuthRolePermission entities in a single operation.
     *
     * @param updateDtos Set of DTOs containing update data for multiple AuthRolePermissions
     * @return List of AuthRolePermissionDetailDTO for the updated entities
     * @throws RuntimeException if any related entities are not found
     */
    @Transactional
    public List<AuthRolePermissionDetailDTO> multiUpdate(Set<AuthRolePermissionUpdateDTO> updateDtos) {
        List<AuthRolePermissionDetailDTO> updatedEntities = new ArrayList<>();
        
        for (AuthRolePermissionUpdateDTO updateDto : updateDtos) {
            if (updateDto.getId() == null) {
                continue;
            }

            Optional<AuthRolePermission> entityOpt = findById(updateDto.getId());
            if (entityOpt.isPresent()) {
                AuthRolePermission entity = entityOpt.get();
                AuthRolePermissionDetailDTO updatedEntity = update(entity, updateDto);
                updatedEntities.add(updatedEntity);
            }
        }
        
        return updatedEntities;
    }

    /**
     * Performs batch updates on multiple AuthRolePermission entities.
     *
     * @param dto DTO containing the batch update data and target IDs
     * @throws RuntimeException if any related entities are not found
     */
    @Transactional
    public void batchUpdate(AuthRolePermissionBatchUpdateDTO dto) {
        List<AuthRolePermission> entities = findAllById(dto.getIds());
        
        entities.forEach(entity -> {
            
            if (dto.getListPermission() != null) {
                entity.setListPermission(dto.getListPermission());
            }
            
            if (dto.getViewPermission() != null) {
                entity.setViewPermission(dto.getViewPermission());
            }
            
            if (dto.getCreatePermission() != null) {
                entity.setCreatePermission(dto.getCreatePermission());
            }
            
            if (dto.getEditPermission() != null) {
                entity.setEditPermission(dto.getEditPermission());
            }
            
            if (dto.getDeletePermission() != null) {
                entity.setDeletePermission(dto.getDeletePermission());
            }
            
            if (dto.getExtra1Permission() != null) {
                entity.setExtra1Permission(dto.getExtra1Permission());
            }
            
            if (dto.getExtra2Permission() != null) {
                entity.setExtra2Permission(dto.getExtra2Permission());
            }
            
            if (dto.getExtra3Permission() != null) {
                entity.setExtra3Permission(dto.getExtra3Permission());
            }
            
            if (dto.getExtra4Permission() != null) {
                entity.setExtra4Permission(dto.getExtra4Permission());
            }
            
            if (dto.getExtra5Permission() != null) {
                entity.setExtra5Permission(dto.getExtra5Permission());
            }
            
        });
        
        saveAll(entities);
    }

    //----------------------------------

    /**
     * Saves a AuthRolePermission entity and returns its projection.
     * Handles the relationships with other entities.
     *
     * @param entity The AuthRolePermission entity to save
     * @param dto The DTO containing relationship data
     * @return AuthRolePermissionDetailDTO of the saved entity
     * @throws RuntimeException if saving fails or if related entities are not found
     */
    private AuthRolePermissionDetailDTO saveAndGetProjection(AuthRolePermission entity, AuthRolePermissionUpdateDTO dto) {
        
        //----------------------------------
        // Many-to-one relationships
        //----------------------------------
        
        // AuthPermission
        String permission = dto.getPermission();
        if (permission != null) {
            AuthPermissionService authPermissionService = authPermissionServiceProvider.getIfAvailable();
            if (authPermissionService != null) {
                entity.setPermission(authPermissionService.findById(permission)
                    .orElseThrow(() -> new RuntimeException("AuthPermission not found")));
            }
        }
                
        // UserRole
        String role = dto.getRole();
        if (role != null) {
            UserRoleService userRoleService = userRoleServiceProvider.getIfAvailable();
            if (userRoleService != null) {
                entity.setRole(userRoleService.findById(role)
                    .orElseThrow(() -> new RuntimeException("UserRole not found")));
            }
        }
                
        // UserOrganization
        String organization = dto.getOrganization();
        if (organization != null) {
            UserOrganizationService userOrganizationService = userOrganizationServiceProvider.getIfAvailable();
            if (userOrganizationService != null) {
                entity.setOrganization(userOrganizationService.findById(organization)
                    .orElseThrow(() -> new RuntimeException("UserOrganization not found")));
            }
        }
                
        // UserAccount
        String userAccount = dto.getUserAccount();
        if (userAccount != null) {
            UserAccountService userAccountService = userAccountServiceProvider.getIfAvailable();
            if (userAccountService != null) {
                entity.setUserAccount(userAccountService.findById(userAccount)
                    .orElseThrow(() -> new RuntimeException("UserAccount not found")));
            }
        }
                

        //----------------------------------
        // Many-to-many relationships
        //----------------------------------
        
        

        AuthRolePermission savedEntity = saveAndFlush(entity);
        return findById(savedEntity.getId(), AuthRolePermissionDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("Failed to retrieve saved entity"));
    }

    //----------------------------------
    
    /**
     * Checks if the current user has the specified permission for the entity.
     * 
     * @param permission The permission to check (e.g., "view", "edit", "delete")
     * @param id The ID of the entity to check permissions for. Can be null for new entities
     * @param dto The DTO object containing entity data. Used when id is null
     * @return true if the user has the permission, false otherwise
     * @throws RuntimeException if the entity is not found with the given id
     */
    @Override
    public boolean hasOwnerPermission(String permission, String id, Object dto) {
        // TODO must be implemented

        // // Example implementation
        // AuthRolePermission entity = new AuthRolePermission();
        // if (id != null) {
        //     entity = findById(id).orElseThrow(() -> new RuntimeException("AuthRolePermission not found"));
        // } else {
        //     modelMapper.map(dto, entity);
        // }

        // Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        // if (Set.of("view", "edit", "delete").contains(permission)) {
        //     return auth.getName().equals(entity.getUsername());
        // }

        throw new UnsupportedOperationException("Unimplemented method 'hasPermission'");
    }
} 