package dev.simplecore.simplix.demo.web.common.auth.controller.web;

import dev.simplecore.simplix.demo.web.common.auth.dto.AuthPermissionDTOs.*;
import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthPermission;
import dev.simplecore.simplix.demo.web.common.auth.service.AuthPermissionService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:04:09.015+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * Permission Settings
 *
 */
@Controller
@RequestMapping("/auth/permission")
public class AuthPermissionController extends SimpliXBaseController<AuthPermission, String> {

    private final AuthPermissionService service;

    /**
     * Constructor for AuthPermissionController
     *
     * @param service The service instance for handling AuthPermission operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    protected AuthPermissionController(AuthPermissionService service) {
        super(service);
        this.service = service;

    }

    /**
     * Displays the list page for AuthPermission entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/list")
    public String list(Model model) {
        model.addAttribute("pageTitle", "Permission Settings Management");
        addSelectData(model);
        return "auth/permission/list";
    }

    /**
     * Displays the detail page for a AuthPermission entity
     *
     * @param id The ID of the AuthPermission to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/detail/{id}")
    public String detail(@PathVariable String id, Model model) {
        model.addAttribute("pageTitle", "Permission Settings Details");
        return service.findById(id, AuthPermissionDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "auth/permission/detail";
            })
            .orElse("redirect:/auth/permission/list");
    }

    /**
     * Returns the brief content fragment for a AuthPermission entity
     *
     * @param id The ID of the AuthPermission to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/brief/{id}")
    public String getBrief(@PathVariable String id, Model model) {
        service.findById(id, AuthPermissionDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "auth/permission/detail :: brief-content";
    }

    /**
     * Displays the edit page for a AuthPermission entity
     *
     * @param id The ID of the AuthPermission to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/edit/{id}")
    public String edit(@PathVariable String id, Model model) {
        AuthPermissionDetailDTO item = service.findById(id, AuthPermissionDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("AuthPermission not found"));
        
        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "Edit Permission Settings");
        addSelectData(model);
        
        return "auth/permission/edit";
    }

    /**
     * Displays the create page for a new AuthPermission entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/create")
    public String create(Model model) {
        model.addAttribute("pageTitle", "Register Permission Settings");
        addSelectData(model);

        return "auth/permission/edit";
    }
    
    //----------------------------------------------------------
    
    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    private void addSelectData(Model model) {

    }
} 