package dev.simplecore.simplix.demo.web.common.auth.controller.web;

import dev.simplecore.simplix.demo.web.common.auth.dto.AuthPermissionDTOs.*;
import dev.simplecore.simplix.demo.web.common.auth.dto.AuthRolePermissionDTOs.*;
import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthRolePermission;
import dev.simplecore.simplix.demo.web.common.auth.service.AuthPermissionService;
import dev.simplecore.simplix.demo.web.common.auth.service.AuthRolePermissionService;
import dev.simplecore.simplix.demo.web.common.user.dto.UserAccountDTOs.UserAccountSearchDTO;
import dev.simplecore.simplix.demo.web.common.user.dto.UserOrganizationDTOs.UserOrganizationSearchDTO;
import dev.simplecore.simplix.demo.web.common.user.dto.UserRoleDTOs.UserRoleSearchDTO;
import dev.simplecore.simplix.demo.web.common.user.service.UserAccountService;
import dev.simplecore.simplix.demo.web.common.user.service.UserOrganizationService;
import dev.simplecore.simplix.demo.web.common.user.service.UserRoleService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.core.condition.SearchConditionBuilder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T18:46:02.603+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * Role-based Permission Settings
 *
 */
@Controller
@RequestMapping("/auth-role-permission")
public class AuthRolePermissionController extends SimpliXBaseController<AuthRolePermission, String> {

    private final AuthRolePermissionService service;

    private final AuthPermissionService authPermissionService;
    private final UserRoleService userRoleService;
    private final UserOrganizationService userOrganizationService;
    private final UserAccountService userAccountService;
    /**
     * Constructor for AuthRolePermissionController
     *
     * @param service The service instance for handling AuthRolePermission operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    protected AuthRolePermissionController(AuthRolePermissionService service,
            AuthPermissionService authPermissionService,
            UserRoleService userRoleService,
            UserOrganizationService userOrganizationService,
            UserAccountService userAccountService) {
        super(service);
        this.service = service;

        this.authPermissionService = authPermissionService;
        this.userRoleService = userRoleService;
        this.userOrganizationService = userOrganizationService;
        this.userAccountService = userAccountService;
    }

    /**
     * Displays the list page for AuthRolePermission entities
     *
     * @param model Spring MVC Model
     * @return The view name for the list page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    @GetMapping("/list")
    public String list(Model model) {
        model.addAttribute("pageTitle", "Role-based Permission Settings Management");
        addSelectData(model);
        return "auth-role-permission/list";
    }

    /**
     * Displays the detail page for a AuthRolePermission entity
     *
     * @param id The ID of the AuthRolePermission to display
     * @param model Spring MVC Model
     * @return The view name for the detail page or redirect to list
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    @GetMapping("/detail/{id}")
    public String detail(@PathVariable String id, Model model) {
        model.addAttribute("pageTitle", "Role-based Permission Settings Details");
        return service.findById(id, AuthRolePermissionDetailDTO.class)
            .map(item -> {
                model.addAttribute("item", item);
                return "auth-role-permission/detail";
            })
            .orElse("redirect:/auth-role-permission/list");
    }

    /**
     * Returns the brief content fragment for a AuthRolePermission entity
     *
     * @param id The ID of the AuthRolePermission to display
     * @param model Spring MVC Model
     * @return The fragment name for brief content
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    @GetMapping("/brief/{id}")
    public String getBrief(@PathVariable String id, Model model) {
        service.findById(id, AuthRolePermissionDetailDTO.class)
            .ifPresent(item -> model.addAttribute("item", item));
        return "auth-role-permission/detail :: brief-content";
    }

    /**
     * Displays the edit page for a AuthRolePermission entity
     *
     * @param id The ID of the AuthRolePermission to edit
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    @GetMapping("/edit/{id}")
    public String edit(@PathVariable String id, Model model) {
        AuthRolePermissionDetailDTO item = service.findById(id, AuthRolePermissionDetailDTO.class)
            .orElseThrow(() -> new RuntimeException("AuthRolePermission not found"));
        
        model.addAttribute("item", item);
        model.addAttribute("pageTitle", "Edit Role-based Permission Settings");
        addSelectData(model);
        
        return "auth-role-permission/edit";
    }

    /**
     * Displays the create page for a new AuthRolePermission entity
     *
     * @param model Spring MVC Model
     * @return The view name for the edit page
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    @GetMapping("/create")
    public String create(Model model) {
        model.addAttribute("pageTitle", "Register Role-based Permission Settings");
        addSelectData(model);

        return "auth-role-permission/edit";
    }
    
    //----------------------------------------------------------
    
    /**
     * Adds select box data to the model
     *
     * @param model Spring MVC Model
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T18:46:02.603+09:00
     */
    private void addSelectData(Model model) {

        SearchCondition<AuthPermissionSearchDTO> authPermissionCondition = SearchConditionBuilder
            .create(AuthPermissionSearchDTO.class)
            .build();
        model.addAttribute(
            "permission",
            authPermissionService.findAllWithSearch(authPermissionCondition).getContent()
        );

        SearchCondition<UserRoleSearchDTO> userRoleCondition = SearchConditionBuilder
            .create(UserRoleSearchDTO.class)
            .build();
        model.addAttribute(
            "role",
            userRoleService.findAllWithSearch(userRoleCondition).getContent()
        );

        SearchCondition<UserOrganizationSearchDTO> userOrganizationCondition = SearchConditionBuilder
            .create(UserOrganizationSearchDTO.class)
            .build();
        model.addAttribute(
            "organization",
            userOrganizationService.findAllWithSearch(userOrganizationCondition).getContent()
        );

        SearchCondition<UserAccountSearchDTO> userAccountCondition = SearchConditionBuilder
            .create(UserAccountSearchDTO.class)
            .build();
        model.addAttribute(
            "userAccount",
            userAccountService.findAllWithSearch(userAccountCondition).getContent()
        );

    }
} 