package dev.simplecore.simplix.demo.web.common.code.controller.rest;

import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import dev.simplecore.simplix.web.controller.SimpliXStandardApi;
import dev.simplecore.simplix.core.model.SimpliXApiResponse;
import dev.simplecore.simplix.demo.web.common.code.dto.CodeItemDTOs.*;
import dev.simplecore.simplix.demo.domain.common.code.entity.CodeItem;

import dev.simplecore.simplix.demo.web.common.code.service.CodeItemService;
import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.openapi.annotation.SearchableParams;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * This file was auto-generated by SimpliX Generator
 *
 * Generator Version: 0.0.1
 * Generated At: 2025-07-19T00:54:03.879+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */

/**
 * Code Item REST Controller
 *
 * @author Taehwan Kwag
 * @since 2025-07-18
 */
@RestController
@RequestMapping("/api/code/item")
@Tag(name = "common.code.CodeItem", description = "Code Item")
public class CodeItemRestController extends SimpliXBaseController<CodeItem, String> {

    private final CodeItemService service;

    /**
     * Constructor for CodeItemRestController
     *
     * @param service The service instance for handling CodeItem operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    protected CodeItemRestController(CodeItemService service) {
        super(service);
        this.service = service;
    }

    /**
     * Creates a new CodeItem entity
     *
     * @param createDto The DTO containing the data to create a new CodeItem
     * @return ResponseEntity containing the created CodeItemDetailDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @PostMapping("/create")
    @Operation(summary = "Create CodeItem", description = "Creates a new code item")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'create')")
    public ResponseEntity<SimpliXApiResponse<CodeItemDetailDTO>> create(
        @RequestBody @Validated CodeItemCreateDTO createDto) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.create(createDto)));
    }

    /**
     * Updates an existing CodeItem entity
     *
     * @param codeItemId The ID of the CodeItem to update
     * @param updateDto The DTO containing the updated data
     * @return ResponseEntity containing the updated CodeItemDetailDTO or 404 if not found
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @PutMapping("/{codeItemId}")
    @Operation(summary = "Update CodeItem", description = "Updates existing code item")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'edit')")
    public ResponseEntity<SimpliXApiResponse<CodeItemDetailDTO>> update(
        @PathVariable String codeItemId, 
        @RequestBody @Validated CodeItemUpdateDTO updateDto) {

        return service.findById(codeItemId)
                .map(entity -> ResponseEntity.ok(SimpliXApiResponse.success(service.update(entity, updateDto))))
                .orElse(ResponseEntity.ok(SimpliXApiResponse.failure(null, "CodeItem not found")));
    }

    /**
     * Updates multiple CodeItem entities in a single operation
     *
     * @param updateDtos Set of DTOs containing the data to update multiple CodeItem
     * @return ResponseEntity containing the list of updated CodeItemDetailDTOs and success status
     * @throws IllegalArgumentException if any of the updateDtos are invalid
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @PatchMapping
    @Operation(summary = "Update Multiple CodeItem", description = "Updates multiple existing code items")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'edit')")
    public ResponseEntity<SimpliXApiResponse<List<CodeItemDetailDTO>>> multiUpdate(
        @RequestBody Set<CodeItemUpdateDTO> updateDtos) {
        List<CodeItemDetailDTO> updatedItems = service.multiUpdate(updateDtos);
        
        return ResponseEntity.ok(SimpliXApiResponse.success(updatedItems));
    }

    /**
     * Deletes a CodeItem by its ID
     *
     * @param codeItemId The ID of the CodeItem to delete
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @DeleteMapping("/{codeItemId}")
    @Operation(summary = "Delete CodeItem", description = "Deletes code item by ID")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'delete')")
    public ResponseEntity<SimpliXApiResponse<Void>> delete(
        @PathVariable String codeItemId) {
        
        if (!service.existsById(codeItemId)) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "CodeItem not found"));
        }
        service.delete(codeItemId);
        
        return ResponseEntity.ok(SimpliXApiResponse.success(null, "CodeItem deleted successfully"));
    }

    /**
     * Retrieves a CodeItem by its ID
     *
     * @param codeItemId The ID of the CodeItem to retrieve
     * @return ResponseEntity containing the found CodeItemDetailDTO or 404 if not found
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @GetMapping("/{codeItemId}")
    @Operation(summary = "Get CodeItem", description = "Retrieves code item by ID")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'view')")
    public ResponseEntity<SimpliXApiResponse<CodeItemDetailDTO>> get(
        @PathVariable String codeItemId) {

        return service.findById(codeItemId, CodeItemDetailDTO.class)
                .map(result -> ResponseEntity.ok(SimpliXApiResponse.success(result)))
                .orElse(ResponseEntity.ok(SimpliXApiResponse.failure(null, "CodeItem not found")));
    }

    /**
     * Batch updates multiple CodeItem entities
     *
     * @param batchUpdateDto The DTO containing the batch update data
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @PatchMapping("/batch")
    @Operation(summary = "Batch Update CodeItems", description = "Updates multiple code items")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'edit')")
    public ResponseEntity<SimpliXApiResponse<Void>> batchUpdate(@RequestBody @Validated CodeItemBatchUpdateDTO batchUpdateDto) {
        try {
            service.batchUpdate(batchUpdateDto);
            return ResponseEntity.ok(SimpliXApiResponse.success(null, "CodeItems updated successfully"));
        } catch (Exception e) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "Failed to process batch update"));
        }
    }

    /**
     * Deletes multiple CodeItem entities by their IDs
     * 
     * @param codeItemIds List of IDs of the CodeItem entities to delete
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @DeleteMapping("/batch")
    @Operation(summary = "Delete multiple CodeItems", description = "Deletes multiple code items by their IDs")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'delete')")
    public ResponseEntity<SimpliXApiResponse<Void>> batchDelete(@RequestParam List<String> codeItemIds) {
        service.batchDelete(codeItemIds);
        
        return ResponseEntity.ok(SimpliXApiResponse.success(null, "CodeItems deleted successfully"));
    }

    //----------------------------------
    // Searchable JPA
    //----------------------------------

    /**
     * Search CodeItem entities with GET method
     *
     * @param params Map of search parameters
     * @return ResponseEntity containing a page of CodeItemListDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @GetMapping("/search")
    @Operation(summary = "Search CodeItem list (GET)", description = "Searches code items with various conditions using GET method")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'list')")
    public ResponseEntity<SimpliXApiResponse<Page<CodeItemListDTO>>> simpleSearch(
        @RequestParam(required = false) @SearchableParams(CodeItemSearchDTO.class) Map<String, String> params
    ) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.search(params)));
    }

    /**
     * Search CodeItem entities with POST method
     *
     * @param searchCondition The search conditions for filtering CodeItems
     * @return ResponseEntity containing a page of CodeItemListDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-07-19T00:54:03.879+09:00
     */
    @PostMapping("/search")
    @Operation(summary = "Search CodeItem list (POST)", description = "Searches code items with various conditions using POST method")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('CodeItem', 'list')")
    public ResponseEntity<SimpliXApiResponse<Page<CodeItemListDTO>>> search(
        @RequestBody @Validated SearchCondition<CodeItemSearchDTO> searchCondition
    ) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.search(searchCondition)));
    }
}
