package dev.simplecore.simplix.demo.web.common.user.controller.rest;

import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.openapi.annotation.SearchableParams;
import dev.simplecore.simplix.core.model.SimpliXApiResponse;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import dev.simplecore.simplix.demo.web.common.user.dto.UserRoleDTOs.*;
import dev.simplecore.simplix.demo.web.common.user.service.UserRoleService;
import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import dev.simplecore.simplix.web.controller.SimpliXStandardApi;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-06T10:21:42.982+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * REST Controller for user roles.
 *
 * @author thkwag
 * @since 2025-02-06
 */
@RestController
@RequestMapping("/api/user/role")
@Tag(name = "common.user.UserRole", description = "User Role")
public class UserRoleRestController extends SimpliXBaseController<UserRole, String> {

    private final UserRoleService service;

    /**
     * Constructor for UserRoleRestController
     *
     * @param service The service instance for handling UserRole operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    protected UserRoleRestController(UserRoleService service) {
        super(service);
        this.service = service;
    }


    /**
     * Creates a new UserRole entity
     *
     * @param createDto The DTO containing the data to create a new UserRole
     * @return ResponseEntity containing the created UserRoleDetailDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @PostMapping("/create")
    @Operation(summary = "Create UserRole", description = "Creates a new user role")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'create')")
    public ResponseEntity<SimpliXApiResponse<UserRoleDetailDTO>> create(
        @RequestBody @Validated UserRoleCreateDTO createDto) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.create(createDto)));
    }
    

    /**
     * Updates an existing UserRole entity
     *
     * @param id The ID of the UserRole to update
     * @param updateDto The DTO containing the updated data
     * @return ResponseEntity containing the updated UserRoleDetailDTO or 404 if not found
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @PutMapping("/{id}")
    @Operation(summary = "Update UserRole", description = "Updates existing user role")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'edit')")
    public ResponseEntity<SimpliXApiResponse<UserRoleDetailDTO>> update(
        @PathVariable String id, @RequestBody @Validated UserRoleUpdateDTO updateDto) {
        return service.findById(id)
                .map(entity -> ResponseEntity.ok(SimpliXApiResponse.success(service.update(entity, updateDto))))
                .orElse(ResponseEntity.ok(SimpliXApiResponse.failure(null, "UserRole not found")));
    }


     /**
      * Updates multiple UserRole entities in a single operation
      *
      * @param updateDtos Set of DTOs containing the data to update multiple UserRole
      * @return ResponseEntity containing the list of updated UserRoleDetailDTOs and success status
      * @throws IllegalArgumentException if any of the updateDtos are invalid
      * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
      */
      @PatchMapping
      @Operation(summary = "Update Multiple UserRole", description = "Updates multiple existing user roles")
      @SimpliXStandardApi
      @PreAuthorize("hasPermission('UserRole', 'edit')")
      public ResponseEntity<SimpliXApiResponse<List<UserRoleDetailDTO>>> multiUpdate(
        @RequestBody Set<UserRoleUpdateDTO> updateDtos) {
          List<UserRoleDetailDTO> updatedItems = service.multiUpdate(updateDtos);
          return ResponseEntity.ok(SimpliXApiResponse.success(updatedItems));
      }

    /**
     * Updates the order of multiple UserRole entities
     *
     * @param orderUpdateDtos List of DTOs containing the IDs and new order values
     * @return ResponseEntity containing the list of updated UserRoleDetailDTOs
     */
    @PatchMapping("/order")
    @Operation(summary = "Update UserRole Orders", description = "Updates the order of multiple user roles")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'edit')")
    public ResponseEntity<SimpliXApiResponse<List<UserRoleDetailDTO>>> updateOrder(
        @RequestBody @Validated List<UserRoleOrderUpdateDTO> orderUpdateDtos) {
        try {
            List<UserRoleDetailDTO> updatedRoles = service.updateOrders(orderUpdateDtos);
            return ResponseEntity.ok(SimpliXApiResponse.success(updatedRoles, "UserRole orders updated successfully"));
        } catch (RuntimeException e) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, e.getMessage()));
        }
    }


    /**
     * Deletes a UserRole by its ID
     *
     * @param id The ID of the UserRole to delete
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @DeleteMapping("/{id}")
    @Operation(summary = "Delete UserRole", description = "Deletes user role by ID")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'delete')")
    public ResponseEntity<SimpliXApiResponse<Void>> delete(@PathVariable String id) {
        if (!service.existsById(id)) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "UserRole not found"));
        }
        service.delete(id);
        return ResponseEntity.ok(SimpliXApiResponse.success(null, "UserRole deleted successfully"));
    }


    /**
     * Retrieves a UserRole by its ID
     *
     * @param id The ID of the UserRole to retrieve
     * @return ResponseEntity containing the found UserRoleDetailDTO or 404 if not found
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/{id}")
    @Operation(summary = "Get UserRole", description = "Retrieves user role by ID")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'view')")
    public ResponseEntity<SimpliXApiResponse<UserRoleDetailDTO>> get(@PathVariable String id) {
        return service.findById(id, UserRoleDetailDTO.class)
                .map(result -> ResponseEntity.ok(SimpliXApiResponse.success(result)))
                .orElse(ResponseEntity.ok(SimpliXApiResponse.failure(null, "UserRole not found")));
    }


    /**
     * Batch updates multiple UserRole entities
     *
     * @param batchUpdateDto The DTO containing the batch update data
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @PatchMapping("/batch")
    @Operation(summary = "Batch Update UserRoles", description = "Updates multiple user roles")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'edit')")
    public ResponseEntity<SimpliXApiResponse<Void>> batchUpdate(@RequestBody @Validated UserRoleBatchUpdateDTO batchUpdateDto) {
        try {
            service.batchUpdate(batchUpdateDto);
            return ResponseEntity.ok(SimpliXApiResponse.success(null, "UserRoles updated successfully"));
        } catch (Exception e) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "Failed to process batch update"));
        }
    }

    /**
     * Deletes multiple UserRole entities by their IDs
     *
     * @param ids List of IDs of the UserRole entities to delete
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @DeleteMapping("/batch")
    @Operation(summary = "Delete multiple UserRoles", description = "Deletes multiple user roles by their IDs")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'delete')")
    public ResponseEntity<SimpliXApiResponse<Void>> batchDelete(@RequestParam List<String> ids) {
        try {
            service.batchDelete(ids);
            return ResponseEntity.ok(SimpliXApiResponse.success(null, "UserRoles deleted successfully"));
        } catch (Exception e) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "Failed to process batch delete"));
        }
    }


    //----------------------------------
    // Searchable JPA
    //----------------------------------

    /**
     * Search UserRole entities with GET method
     *
     * @param params Map of search parameters
     * @return ResponseEntity containing a page of UserRoleListDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @GetMapping("/search")
    @Operation(summary = "Search UserRole list (GET)", description = "Searches user roles with various conditions using GET method")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'list')")
    public ResponseEntity<SimpliXApiResponse<Page<UserRoleListDTO>>> simpleSearch(
        @RequestParam(required = false) @SearchableParams(UserRoleSearchDTO.class) Map<String, String> params
    ) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.search(params)));
    }

    /**
     * Search UserRole entities with POST method
     *
     * @param searchCondition The search conditions for filtering UserRoles
     * @return ResponseEntity containing a page of UserRoleListDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-06T10:21:42.982+09:00
     */
    @PostMapping("/search")
    @Operation(summary = "Search UserRole list (POST)", description = "Searches user roles with various conditions using POST method")
    @SimpliXStandardApi
    @PreAuthorize("hasPermission('UserRole', 'list')")
    public ResponseEntity<SimpliXApiResponse<Page<UserRoleListDTO>>> search(
        @RequestBody @Validated SearchCondition<UserRoleSearchDTO> searchCondition
    ) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.search(searchCondition)));
    }
}
