package dev.simplecore.simplix.demo.web.common.user.dto;

// import entity.user.common.domain.dev.simplecore.simplix.demo.UserAccountLog;

import dev.simplecore.searchable.core.annotation.SearchableField;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccountLog.UserAccountLogId;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import jakarta.validation.constraints.NotNull;
import java.time.OffsetDateTime;
import java.util.Set;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-04-27T19:16:32.131+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */
public class UserAccountLogDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserAccountLogSearchDTO {
        
        @Schema(description = "userId")
        @SearchableField(entityField = "id.userId", operators = {EQUALS, CONTAINS})
        private String userId;
        
        @Schema(description = "logTime")
        @SearchableField(entityField = "id.logTime", operators = {BETWEEN, GREATER_THAN, LESS_THAN}, sortable = true)
        private OffsetDateTime logTime;

        @Schema(description = "Log Message")
        @SearchableField(operators = {CONTAINS})
        private String logMessage;
        
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserAccountLogCreateDTO {

        @Schema(description = "UserAccountLog ID")
        private UserAccountLogId id;

        @Schema(description = "Log Message")
        private String logMessage;
        
    }

    @Data
    public static class UserAccountLogUpdateDTO {

        @Schema(description = "UserAccountLog ID")
        @NotNull(message = "ID is a required input value")
        private UserAccountLogId id;

        @Schema(description = "Log Message")
        private String logMessage;
        
    }

    @Data
    public static class UserAccountLogBatchUpdateDTO {

        @Schema(description = "UserAccountLog ID 목록")
        private Set<UserAccountLogId> ids;

        @Schema(description = "Log Message")
        private String logMessage;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserAccountLogDetailDTO {

        @Schema(description = "UserAccountLog ID")
        private UserAccountLogId id;

        @Schema(description = "Log Message")
        private String logMessage;
        
    }

    @Data
    public static class UserAccountLogListDTO {

        @Schema(description = "UserAccountLog ID")
        private UserAccountLogId id;

        @Schema(description = "Log Message")
        private String logMessage;
        
    }
} 