package dev.simplecore.simplix.demo.web.common.user.dto;


import dev.simplecore.searchable.core.annotation.SearchableField;
import dev.simplecore.simplix.core.validator.ValidateWith;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserPosition;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.*;
import java.time.OffsetDateTime;
import java.util.Set;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-04T15:58:41.833+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserAccountDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserAccountSearchDTO {
        
        @Schema(description = "User ID")
        @SearchableField(entityField = "userId", operators = {EQUALS})
        private String userId;
        
        @Schema(description = "Login Account")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String username;
        
        @Schema(description = "Account Status")
        @SearchableField(operators = {EQUALS})
        private Boolean enabled;
        
        @Schema(description = "Name")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String realName;
        
        @Schema(description = "Self-introduction")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "Email")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String email;
        
        @Schema(description = "Mobile Phone")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String mobilePhone;
        
        @Schema(description = "Office Phone")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String officePhone;
        
        @Schema(description = "Postal Code")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String postalCode;
        
        @Schema(description = "Address")
        @SearchableField(operators = {CONTAINS})
        private String address;
        
        @Schema(description = "Detailed Address")
        @SearchableField(operators = {CONTAINS})
        private String addressDetail;
        
        @Schema(description = "Position Information")
        @SearchableField(entityField = "position.positionId", sortField = "position.name", operators = {EQUALS}, sortable = true)
        private String positionId;
        
        @Schema(description = "Permission Information")
        @SearchableField(entityField = "roles.roleId", operators = {IN})
        private String roleId;
        
        @Schema(description = "Affiliated Organization")
        @SearchableField(entityField = "organizations.organizationId", operators = {IN})
        private String organizationId;
        
        @Schema(description = "Registration Date/Time")
        @SearchableField(operators = {GREATER_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO, BETWEEN}, sortable = true)
        private OffsetDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserAccountCreateDTO {
        
        @Schema(description = "Username")
        @NotBlank(message = "{validation.required}")
        @Pattern(regexp = "^[a-zA-Z0-9._-]{4,20}$", message = "{validation.username.pattern}")
        @Length(min = 4, max = 20, message = "{validation.range.length}")
        private String username;

        @Schema(description = "Password")
        @NotBlank(message = "{validation.required}")
        @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{5,}$", message = "{validation.password.pattern}")
        private String password;

        @Schema(description = "Account Status")
        @NotNull(message = "{validation.required}")
        private Boolean enabled;

        @Schema(description = "Name")
        @NotBlank(message = "{validation.required}")
        @Length(min = 2, max = 50, message = "{validation.range.length}")
        private String realName;

        @Schema(description = "Self-introduction")
        @Length(max = 500, message = "{validation.max.length}")
        private String description;

        @Schema(description = "Email")
        @NotBlank(message = "{validation.required}")
        @Email(message = "{validation.invalid.format}")
        private String email;

        @Schema(description = "Mobile Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.invalid.format}")
        private String mobilePhone;

        @Schema(description = "Office Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.invalid.format}")
        private String officePhone;

        @Schema(description = "Postal Code")
        @Pattern(regexp = "^\\d{5}$", message = "{validation.invalid.format}")
        private String postalCode;

        @Schema(description = "Address")
        @Length(max = 200, message = "{validation.max.length}")
        private String address;

        @Schema(description = "Detailed Address")
        @Length(max = 200, message = "{validation.max.length}")
        private String addressDetail;

        @Schema(description = "Position Information")
        @NotBlank(message = "{validation.required}")
        @ValidateWith(service = "userPositionService.validateId", message = "{validation.invalid.exists}")
        private String positionId;

        @Schema(description = "Permission Information")
        @NotEmpty(message = "{validation.empty}")
        @Size(min = 1, max = 10, message = "{validation.range.size}")
        private Set<String> roleIds;

        @Schema(description = "Affiliated Organization")
        @NotEmpty(message = "{validation.empty}")
        @Size(min = 1, max = 10, message = "{validation.range.size}")
        private Set<String> organizationIds;
        
    }

    
    @Data
    public static class UserAccountUpdateDTO {
        
        @Schema(description = "UserAccount ID")
        @NotBlank(message = "{validation.required}")
        private String userId;

        @Schema(description = "Username")
        @NotBlank(message = "{validation.required}")
        @Pattern(regexp = "^[a-zA-Z0-9._-]{4,20}$", message = "{validation.username.pattern}")
        @Length(min = 4, max = 20, message = "{validation.range.length}")
        private String username;

        @Schema(description = "Password")
        @Pattern(regexp = "^$|^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{5,}$", message = "{validation.password.pattern}")
        private String password;

        @Schema(description = "Account Status")
        @NotNull(message = "{validation.required}")
        private Boolean enabled;

        @Schema(description = "Name")
        @NotBlank(message = "{validation.required}")
        @Length(min = 2, max = 50, message = "{validation.range.length}")
        private String realName;

        @Schema(description = "Self-introduction")
        @Length(max = 500, message = "{validation.max.length}")
        private String description;

        @Schema(description = "Email")
        @NotBlank(message = "{validation.required}")
        @Email(message = "{validation.invalid.format}")
        private String email;

        @Schema(description = "Mobile Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.invalid.format}")
        private String mobilePhone;

        @Schema(description = "Office Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.invalid.format}")
        private String officePhone;

        @Schema(description = "Postal Code")
        @Pattern(regexp = "^\\d{5}$", message = "{validation.invalid.format}")
        private String postalCode;

        @Schema(description = "Address")
        @Length(max = 200, message = "{validation.max.length}")
        private String address;

        @Schema(description = "Detailed Address")
        @Length(max = 200, message = "{validation.max.length}")
        private String addressDetail;

        @Schema(description = "Position Information")
        @NotBlank(message = "{validation.required}")
        @ValidateWith(service = "userPositionService.validateId", message = "{validation.invalid.exists}")
        private String positionId;

        @Schema(description = "Permission Information")
        @NotEmpty(message = "{validation.empty}")
        @Size(min = 1, max = 10, message = "{validation.range.size}")
        private Set<String> roleIds;

        @Schema(description = "Affiliated Organization")
        @NotEmpty(message = "{validation.empty}")
        @Size(min = 1, max = 10, message = "{validation.range.size}")
        private Set<String> organizationIds;
        
    }

    @Data
    public static class UserAccountBatchUpdateDTO {
        @Schema(description = "UserAccount ID List")
        private Set<String> userIds;

        @Schema(description = "Account Status")
        private Boolean enabled;
        
        @Schema(description = "Position Information")
        private String positionId;
        
        @Schema(description = "Permission Information")
        private Set<String> roleIds;
        
        @Schema(description = "Affiliated Organization")
        private Set<String> organizationIds;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserAccountDetailDTO {
        
        @Schema(description = "User ID")
        private String userId;
        
        @Schema(description = "Login Account")
        private String username;
        
        @Schema(description = "Account Status")
        private Boolean enabled;
        
        @Schema(description = "Name")
        private String realName;

        @Schema(description = "Self-introduction")
        private String description;
        
        @Schema(description = "Email")
        private String email;
        
        @Schema(description = "Mobile Phone")
        private String mobilePhone;
        
        @Schema(description = "Office Phone")
        private String officePhone;
        
        @Schema(description = "Postal Code")
        private String postalCode;
        
        @Schema(description = "Address")
        private String address;
        
        @Schema(description = "Detailed Address")
        private String addressDetail;
        
        @Schema(description = "Position Information")
        private UserPosition position;
        
        @Schema(description = "Permission Information")
        private Set<UserRole> roles;
        
        @Schema(description = "Affiliated Organization")
        private Set<UserOrganization> organizations;
        
        @Schema(description = "Created By")
        private String createdBy;

        @Schema(description = "Created At")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated By")
        private String updatedBy;

        @Schema(description = "Updated At")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class UserAccountListDTO {
        
        @Schema(description = "User ID")
        private String userId;
        
        @Schema(description = "Login Account")
        private String username;
        
        @Schema(description = "Account Status")
        private Boolean enabled;
        
        @Schema(description = "Name")
        private String realName;
        
        @Schema(description = "Email")
        private String email;
        
        @Schema(description = "Mobile Phone")
        private String mobilePhone;
        
        @Schema(description = "Position Information")
        private UserPosition position;
        
        @Schema(description = "Permission Information")
        private Set<UserRole> roles;
        
        @Schema(description = "Affiliated Organization")
        private Set<UserOrganization> organizations;
        
        @Schema(description = "Created At")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;
    }
} 