package dev.simplecore.simplix.demo.web.common.user.dto;


import java.util.*;
import java.time.OffsetDateTime;

import dev.simplecore.simplix.core.annotation.I18nTitle;
import dev.simplecore.simplix.core.validator.ValidateWith;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserPosition;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
import javax.validation.constraints.*;
import org.hibernate.validator.constraints.Length;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-04T15:58:41.833+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserAccountDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserAccountSearchDTO {
        
        @Schema(description = "User ID")
        @SearchableField(operators = {EQUALS})
        private String id;
        
        @Schema(description = "Login Account")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String username;
        
        @Schema(description = "Account Status")
        @SearchableField(operators = {EQUALS})
        private Boolean enabled;
        
        @Schema(description = "Name")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String realName;
        
        @Schema(description = "Self-introduction")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "Email")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String email;
        
        @Schema(description = "Mobile Phone")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String mobilePhone;
        
        @Schema(description = "Office Phone")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String officePhone;
        
        @Schema(description = "Postal Code")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String postalCode;
        
        @Schema(description = "Address")
        @SearchableField(operators = {CONTAINS})
        private String address;
        
        @Schema(description = "Detailed Address")
        @SearchableField(operators = {CONTAINS})
        private String addressDetail;
        
        @Schema(description = "Position Information")
        @SearchableField(entityField = "position.positionId", operators = {EQUALS}, sortable = true)
        private String position;
        
        @Schema(description = "Permission Information")
        @SearchableField(entityField = "roles.roleId", operators = {EQUALS})
        private String roles;
        
        @Schema(description = "Affiliated Organization")
        @SearchableField(entityField = "organizations.organizationId", operators = {EQUALS})
        private String organizations;
        
        @Schema(description = "Registration Date/Time")
        @SearchableField(operators = {GREATER_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO, BETWEEN}, sortable = true)
        private OffsetDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserAccountCreateDTO {
        
        @Schema(description = "Username")
        @NotBlank(message = "{validation.username.required}")
        @Pattern(regexp = "^[a-zA-Z0-9._-]{4,20}$", message = "{validation.username.pattern}")
        @Length(min = 4, max = 20, message = "{validation.username.length}")
        private String username;

        @Schema(description = "Password")
        @NotBlank(message = "{validation.password.required}")
        @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{5,}$", message = "{validation.password.pattern}")
        private String password;
        
        @Schema(description = "Account Status")
        @NotNull(message = "{validation.enabled.required}")
        private Boolean enabled;
        
        @Schema(description = "Name")
        @NotBlank(message = "{validation.realName.required}")
        @Length(min = 2, max = 50, message = "{validation.realName.length}")
        private String realName;
        
        @Schema(description = "Profile Image")
        @Size(max = 5242880, message = "{validation.profileImage.size}")
        private byte[] profileImage;
        
        @Schema(description = "Profile Image Type")
        @Pattern(regexp = "^image/(jpeg|png|gif)$", message = "{validation.profileImageType.pattern}")
        private String profileImageType;
        
        @Schema(description = "Self-introduction")
        @Length(max = 500, message = "{validation.description.length}")
        private String description;
        
        @Schema(description = "Email")
        @NotBlank(message = "{validation.email.required}")
        @Email(message = "{validation.email.format}")
        private String email;
        
        @Schema(description = "Mobile Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.mobilePhone.pattern}")
        private String mobilePhone;
        
        @Schema(description = "Office Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.officePhone.pattern}")
        private String officePhone;
        
        @Schema(description = "Postal Code")
        @Pattern(regexp = "^\\d{5}$", message = "{validation.postalCode.pattern}")
        private String postalCode;
        
        @Schema(description = "Address")
        @Length(max = 200, message = "{validation.address.length}")
        private String address;
        
        @Schema(description = "Detailed Address")
        @Length(max = 200, message = "{validation.addressDetail.length}")
        private String addressDetail;
        
        @Schema(description = "Position Information")
        @NotBlank(message = "{validation.position.required}")
        @ValidateWith(service = "userPositionService.validateId", message = "{validation.position.invalid}")
        private String position;
        
        @Schema(description = "Permission Information")
        @NotEmpty(message = "{validation.roles.required}")
        @Size(min = 1, max = 10, message = "{validation.roles.size}")
        private Set<String> roles;
        
        @Schema(description = "Affiliated Organization")
        @NotEmpty(message = "{validation.organizations.required}")
        @Size(min = 1, max = 10, message = "{validation.organizations.size}")
        private Set<String> organizations;
        
    }

    
    @Data
    public static class UserAccountUpdateDTO {
        
        @Schema(description = "UserAccount ID")
        @NotBlank(message = "{validation.id.required}")
        private String id;

        @Schema(description = "Username")
        @NotBlank(message = "{validation.username.required}")
        @Pattern(regexp = "^[a-zA-Z0-9._-]{4,20}$", message = "{validation.username.pattern}")
        @Length(min = 4, max = 20, message = "{validation.username.length}")
        private String username;
        
        @Schema(description = "Password")
        @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{5,}$", message = "{validation.password.pattern}")
        private String password;
        
        @Schema(description = "계정상태")
        @NotNull(message = "{validation.enabled.required}")
        private Boolean enabled;
        
        @Schema(description = "Name")
        @NotBlank(message = "{validation.realName.required}")
        @Length(min = 2, max = 50, message = "{validation.realName.length}")
        private String realName;
        
        @Schema(description = "Profile Image")
        @Size(max = 5242880, message = "{validation.profileImage.size}")
        private byte[] profileImage;
        
        @Schema(description = "Profile Image Type")
        @Pattern(regexp = "^image/(jpeg|png|gif)$", message = "{validation.profileImageType.pattern}")
        private String profileImageType;
        
        @Schema(description = "Self-introduction")
        @Length(max = 500, message = "{validation.description.length}")
        private String description;
        
        @Schema(description = "Email")
        @NotBlank(message = "{validation.email.required}")
        @Email(message = "{validation.email.format}")
        private String email;
        
        @Schema(description = "Mobile Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.mobilePhone.pattern}")
        private String mobilePhone;
        
        @Schema(description = "Office Phone")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "{validation.officePhone.pattern}")
        private String officePhone;
        
        @Schema(description = "Postal Code")
        @Pattern(regexp = "^\\d{5}$", message = "{validation.postalCode.pattern}")
        private String postalCode;
        
        @Schema(description = "Address")
        @Length(max = 200, message = "{validation.address.length}")
        private String address;
        
        @Schema(description = "Detailed Address")
        @Length(max = 200, message = "{validation.addressDetail.length}")
        private String addressDetail;
        
        @Schema(description = "Position Information")
        @NotBlank(message = "{validation.position.required}")
        @ValidateWith(service = "userPositionService.validateId", message = "{validation.position.invalid}")
        private String position;
        
        @Schema(description = "Permission Information")
        @NotEmpty(message = "{validation.roles.required}")
        @Size(min = 1, max = 10, message = "{validation.roles.size}")
        private Set<String> roles;
        
        @Schema(description = "Affiliated Organization")
        @NotEmpty(message = "{validation.organizations.required}")
        @Size(min = 1, max = 10, message = "{validation.organizations.size}")
        private Set<String> organizations;
        
    }

    @Data
    public static class UserAccountBatchUpdateDTO {
        @Schema(description = "UserAccount ID List")
        private Set<String> ids;
        
        @Schema(description = "계정상태")
        private Boolean enabled;
        
        @Schema(description = "Position Information")
        private String position;
        
        @Schema(description = "Permission Information")
        private Set<String> roles;
        
        @Schema(description = "Affiliated Organization")
        private Set<String> organizations;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserAccountDetailDTO {
        
        @Schema(description = "User ID")
        private String id;
        
        @Schema(description = "Login Account")
        private String username;
        
        @Schema(description = "계정상태")
        private Boolean enabled;
        
        @Schema(description = "이름")
        private String realName;
        
        @Schema(description = "프로필 이미지")
        private byte[] profileImage;
        
        @Schema(description = "Profile Image Type")
        private String profileImageType;
        
        @Schema(description = "Self-introduction")
        private String description;
        
        @Schema(description = "Email")
        private String email;
        
        @Schema(description = "Mobile Phone")
        private String mobilePhone;
        
        @Schema(description = "Office Phone")
        private String officePhone;
        
        @Schema(description = "Postal Code")
        private String postalCode;
        
        @Schema(description = "Address")
        private String address;
        
        @Schema(description = "Detailed Address")
        private String addressDetail;
        
        @Schema(description = "Position Information")
        private UserPosition position;
        
        @Schema(description = "Permission Information")
        private Set<UserRole> roles;
        
        @Schema(description = "Affiliated Organization")
        private Set<UserOrganization> organizations;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class UserAccountListDTO {
        
        @Schema(description = "User ID")
        private String id;
        
        @Schema(description = "Login Account")
        private String username;
        
        @Schema(description = "계정상태")
        private Boolean enabled;
        
        @Schema(description = "이름")
        private String realName;
        
        @Schema(description = "Email")
        private String email;
        
        @Schema(description = "Mobile Phone")
        private String mobilePhone;
        
        @Schema(description = "Position Information")
        private UserPosition position;
        
        @Schema(description = "Permission Information")
        private Set<UserRole> roles;
        
        @Schema(description = "Affiliated Organization")
        private Set<UserOrganization> organizations;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;
    }
} 