package dev.simplecore.simplix.demo.web.common.user.dto;


import java.util.*;
import java.time.LocalDateTime;

import dev.simplecore.simplix.core.validator.ValidateWith;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserPosition;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import com.github.thkwag.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
import javax.validation.constraints.*;
import org.hibernate.validator.constraints.Length;
import dev.simplecore.simplix.excel.annotation.ExcelColumn;

import static com.github.thkwag.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-04T15:58:41.833+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserAccountDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserAccountSearchDTO {
        
        @Schema(description = "사용자 ID")
        @SearchableField(operators = {EQUALS})
        private String id;
        
        @Schema(description = "로그인 계정")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String username;
        
        @Schema(description = "계정상태")
        @SearchableField(operators = {EQUALS})
        private Boolean enabled;
        
        @Schema(description = "이름")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String realName;
        
        @Schema(description = "자기소개")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "이메일")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String email;
        
        @Schema(description = "휴대전화")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String mobilePhone;
        
        @Schema(description = "사무실 전화")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String officePhone;
        
        @Schema(description = "우편번호")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String postalCode;
        
        @Schema(description = "주소")
        @SearchableField(operators = {CONTAINS})
        private String address;
        
        @Schema(description = "상세주소")
        @SearchableField(operators = {CONTAINS})
        private String addressDetail;
        
        @Schema(description = "직급정보")
        @SearchableField(entityField = "position.positionId", operators = {EQUALS}, sortable = true)
        private String position;
        
        @Schema(description = "권한정보")
        @SearchableField(entityField = "roles.roleId", operators = {EQUALS})
        private String roles;
        
        @Schema(description = "소속조직")
        @SearchableField(entityField = "organizations.organizationId", operators = {EQUALS})
        private String organizations;
        
        @Schema(description = "등록일시")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private LocalDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserAccountCreateDTO {
        
        @Schema(description = "사용자명")
        @NotBlank(message = "사용자명은 필수 입력값입니다")
        @Pattern(regexp = "^[a-zA-Z0-9._-]{4,20}$", 
                message = "사용자명은 영문자, 숫자, 점(.), 하이픈(-), 언더스코어(_)만 사용하여 4~20자로 입력해주세요")
        @Length(min = 4, max = 20, message = "사용자명은 4~20자 사이로 입력해주세요")
        private String username;

        @Schema(description = "비밀번호")
        @NotBlank(message = "비밀번호는 반드시 입력하여야합니다.")
        @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{5,}$",
                message = "비밀번호는 5자 이상, 영문, 숫자, 특수문자를 포함해야 합니다")
        private String password;
        
        @Schema(description = "계정상태")
        @NotNull(message = "계정상태는 필수 입력값입니다")
        private Boolean enabled;
        
        @Schema(description = "이름")
        @NotBlank(message = "이름은 필수 입력값입니다")
        @Length(min = 2, max = 50, message = "이름은 2~50자 사이로 입력해주세요")
        private String realName;
        
        @Schema(description = "프로필 이미지")
        @Size(max = 5242880, message = "프로필 이미지는 5MB 이하만 가능합니다")
        private byte[] profileImage;
        
        @Schema(description = "프로필 이미지 타입")
        @Pattern(regexp = "^image/(jpeg|png|gif)$", message = "지원하지 않는 이미지 형식입니다")
        private String profileImageType;
        
        @Schema(description = "자기소개")
        @Length(max = 500, message = "자기소개는 500자 이내로 입력해주세요")
        private String description;
        
        @Schema(description = "이메일")
        @NotBlank(message = "이메일은 필수 입력값입니다")
        @Email(message = "올바른 이메일 형식이 아닙니다")
        private String email;
        
        @Schema(description = "휴대전화")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "올바른 전화번호 형식이 아닙니다")
        private String mobilePhone;
        
        @Schema(description = "사무실 전화")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "올바른 전화번호 형식이 아닙니다")
        private String officePhone;
        
        @Schema(description = "우편번호")
        @Pattern(regexp = "^\\d{5}$", message = "올바른 우편번호 형식이 아닙니다")
        private String postalCode;
        
        @Schema(description = "주소")
        @Length(max = 200, message = "주소는 200자 이내로 입력해주세요")
        private String address;
        
        @Schema(description = "상세주소")
        @Length(max = 200, message = "상세주소는 200자 이내로 입력해주세요")
        private String addressDetail;
        
        @Schema(description = "직급정보")
        @NotBlank(message = "직급정보는 필수 입력값입니다")
        @ValidateWith(service = "userPositionService.validateId", message = "존재하지 않는 직급정보입니다.")
        private String position;
        
        @Schema(description = "권한정보")
        @NotEmpty(message = "최소 하나 이상의 권한이 필요합니다")
        @Size(min = 1, max = 10, message = "권한은 1~10개까지 지정 가능합니다")
        private Set<String> roles;
        
        @Schema(description = "소속조직")
        @NotEmpty(message = "최소 하나 이상의 소속조직이 필요합니다")
        @Size(min = 1, max = 10, message = "소속조직은 1~10개까지 지정 가능합니다")
        private Set<String> organizations;
        
    }

    
    @Data
    public static class UserAccountUpdateDTO {
        
        @Schema(description = "UserAccount ID")
        @NotBlank(message = "ID는 필수 입력값입니다")
        private String id;

        @Schema(description = "사용자명")
        @NotBlank(message = "사용자명은 필수 입력값입니다")
        @Pattern(regexp = "^[a-zA-Z0-9._-]{4,20}$", 
                message = "사용자명은 영문자, 숫자, 점(.), 하이픈(-), 언더스코어(_)만 사용하여 4~20자로 입력해주세요")
        @Length(min = 4, max = 20, message = "사용자명은 4~20자 사이로 입력해주세요")
        private String username;
        
        @Schema(description = "비밀번호")
        @Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{5,}$",
                message = "비밀번호는 5자 이상, 영문, 숫자, 특수문자를 포함해야 합니다")
        private String password;
        
        @Schema(description = "계정상태")
        @NotNull(message = "계정상태는 필수 입력값입니다")
        private Boolean enabled;
        
        @Schema(description = "이름")
        @NotBlank(message = "이름은 필수 입력값입니다")
        @Length(min = 2, max = 50, message = "이름은 2~50자 사이로 입력해주세요")
        private String realName;
        
        @Schema(description = "프로필 이미지")
        @Size(max = 5242880, message = "프로필 이미지는 5MB 이하만 가능합니다")
        private byte[] profileImage;
        
        @Schema(description = "프로필 이미지 타입")
        @Pattern(regexp = "^image/(jpeg|png|gif)$", message = "지원하지 않는 이미지 형식입니다")
        private String profileImageType;
        
        @Schema(description = "자기소개")
        @Length(max = 500, message = "자기소개는 500자 이내로 입력해주세요")
        private String description;
        
        @Schema(description = "이메일")
        @NotBlank(message = "이메일은 필수 입력값입니다")
        @Email(message = "올바른 이메일 형식이 아닙니다")
        private String email;
        
        @Schema(description = "휴대전화")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "올바른 전화번호 형식이 아닙니다")
        private String mobilePhone;
        
        @Schema(description = "사무실 전화")
        @Pattern(regexp = "^\\d{2,3}-\\d{3,4}-\\d{4}$", message = "올바른 전화번호 형식이 아닙니다")
        private String officePhone;
        
        @Schema(description = "우편번호")
        @Pattern(regexp = "^\\d{5}$", message = "올바른 우편번호 형식이 아닙니다")
        private String postalCode;
        
        @Schema(description = "주소")
        @Length(max = 200, message = "주소는 200자 이내로 입력해주세요")
        private String address;
        
        @Schema(description = "상세주소")
        @Length(max = 200, message = "상세주소는 200자 이내로 입력해주세요")
        private String addressDetail;
        
        @Schema(description = "직급정보")
        @NotBlank(message = "직급정보는 필수 입력값입니다")
        @ValidateWith(service = "userPositionService.validateId", message = "존재하지 않는 직급정보입니다.")
        private String position;
        
        @Schema(description = "권한정보")
        @NotEmpty(message = "최소 하나 이상의 권한이 필요합니다")
        @Size(min = 1, max = 10, message = "권한은 1~10개까지 지정 가능합니다")
        private Set<String> roles;
        
        @Schema(description = "소속조직")
        @NotEmpty(message = "최소 하나 이상의 소속조직이 필요합니다")
        @Size(min = 1, max = 10, message = "소속조직은 1~10개까지 지정 가능합니다")
        private Set<String> organizations;
        
    }

    @Data
    public static class UserAccountBatchUpdateDTO {
        @Schema(description = "UserAccount ID 목록")
        private Set<String> ids;
        
        @Schema(description = "계정상태")
        private Boolean enabled;
        
        @Schema(description = "직급정보")
        private String position;
        
        @Schema(description = "권한정보")
        private Set<String> roles;
        
        @Schema(description = "소속조직")
        private Set<String> organizations;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserAccountDetailDTO {
        
        @Schema(description = "사용자 ID")
        private String id;
        
        @Schema(description = "로그인 계정")
        private String username;
        
        @Schema(description = "비밀번호")
        private String password;
        
        @Schema(description = "계정상태")
        private Boolean enabled;
        
        @Schema(description = "이름")
        private String realName;
        
        @Schema(description = "프로필 이미지")
        private byte[] profileImage;
        
        @Schema(description = "프로필 이미지 타입")
        private String profileImageType;
        
        @Schema(description = "자기소개")
        private String description;
        
        @Schema(description = "이메일")
        private String email;
        
        @Schema(description = "휴대전화")
        private String mobilePhone;
        
        @Schema(description = "사무실 전화")
        private String officePhone;
        
        @Schema(description = "우편번호")
        private String postalCode;
        
        @Schema(description = "주소")
        private String address;
        
        @Schema(description = "상세주소")
        private String addressDetail;
        
        @Schema(description = "직급정보")
        private UserPosition position;
        
        @Schema(description = "권한정보")
        private Set<UserRole> roles;
        
        @Schema(description = "소속조직")
        private Set<UserOrganization> organizations;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime updatedAt;
    }

    @Data
    public static class UserAccountListDTO {
        
        @Schema(description = "사용자 ID")
        @ExcelColumn(name = "사용자 ID", order = 1)
        private String id;
        
        @Schema(description = "로그인 계정")
        @ExcelColumn(name = "로그인 계정", order = 2)
        private String username;
        
        @Schema(description = "계정상태")
        @ExcelColumn(name = "계정상태", order = 3)
        private Boolean enabled;
        
        @Schema(description = "이름")
        @ExcelColumn(name = "이름", order = 4)
        private String realName;
        
        @Schema(description = "이메일")
        @ExcelColumn(name = "이메일", order = 5)
        private String email;
        
        @Schema(description = "휴대전화")
        @ExcelColumn(name = "휴대전화", order = 6)
        private String mobilePhone;
        
        @Schema(description = "직급정보")
        @ExcelColumn(name = "직급", order = 7)
        private UserPosition position;
        
        @Schema(description = "권한정보")
        @ExcelColumn(name = "권한", order = 8)
        private Set<UserRole> roles;
        
        @Schema(description = "소속조직")
        @ExcelColumn(name = "소속조직", order = 9)
        private Set<UserOrganization> organizations;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        @ExcelColumn(name = "등록일시", order = 10, format = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;
    }
} 