package dev.simplecore.simplix.demo.web.common.user.dto;

import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotBlank;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Set;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-06T10:21:42.982+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserRoleDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserRoleSearchDTO {
        
        @Schema(description = "Role ID")
        @SearchableField(operators = {CONTAINS, EQUALS})
        private String id;
        
        @Schema(description = "Role Name")
        @SearchableField(operators = {CONTAINS, EQUALS})
        private String name;
        
        @Schema(description = "Role Code")
        @SearchableField(operators = {EQUALS})
        private String role;
        
        @Schema(description = "Role Description")
        @SearchableField(operators = {CONTAINS})
        private String description;

        @Schema(description = "Order")
        @SearchableField(sortable = true)
        private BigDecimal itemOrder;
        
        @Schema(description = "Registration Date/Time")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN})
        private OffsetDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserRoleCreateDTO {
        @Schema(description = "Role Name")
        private String name;
        
        @Schema(description = "Role Code")
        private String role;
        
        @Schema(description = "Role Description")
        private String description;
        
        @Schema(description = "Order")
        private BigDecimal itemOrder;
        
    }

    @Data
    public static class UserRoleUpdateDTO {
        
        @Schema(description = "UserRole ID")
        @NotBlank(message = "ID is a required input value")
        private String id;
        
        @Schema(description = "Role Name")
        private String name;
        
        @Schema(description = "Role Code")
        private String role;
        
        @Schema(description = "Role Description")
        private String description;
        
        @Schema(description = "Order")
        private BigDecimal itemOrder;
        
    }

    @Data
    public static class UserRoleBatchUpdateDTO {
        @Schema(description = "UserRole ID List")
        private Set<String> ids;
        
    }

    @Data
    public static class UserRoleOrderUpdateDTO {
        @Schema(description = "UserRole ID")
        @NotBlank(message = "ID is a required input value")
        private String id;
        
        @Schema(description = "Order")
        private BigDecimal itemOrder;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserRoleDetailDTO {
        
        @Schema(description = "Role ID")
        private String id;
        
        @Schema(description = "Role Name")
        private String name;
        
        @Schema(description = "Role Code")
        private String role;
        
        @Schema(description = "Role Description")
        private String description;
        
        @Schema(description = "Order")
        private BigDecimal itemOrder;
        
        @Schema(description = "Registered By")
        private String createdBy;

        @Schema(description = "Registration Date/Time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Modified By")
        private String updatedBy;

        @Schema(description = "Modification Date/Time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class UserRoleListDTO {
        
        @Schema(description = "Role ID")
        private String id;
        
        @Schema(description = "Role Name")
        private String name;
        
        @Schema(description = "Role Code")
        private String role;
        
        @Schema(description = "Role Description")
        private String description;
        
        @Schema(description = "Order")
        private BigDecimal itemOrder;
        
        @Schema(description = "Registration Date/Time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;
    }
} 