package dev.simplecore.simplix.demo.web.common.user.dto;

import java.time.LocalDateTime;
import java.util.Set;

import javax.validation.constraints.NotBlank;

import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-06T10:21:42.982+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserRoleDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserRoleSearchDTO {
        
        @Schema(description = "역할 ID")
        @SearchableField(operators = {CONTAINS, EQUALS})
        private String id;
        
        @Schema(description = "역할명")
        @SearchableField(operators = {CONTAINS, EQUALS}, sortable = true)
        private String name;
        
        @Schema(description = "역할코드")
        @SearchableField(operators = {EQUALS})
        private String role;
        
        @Schema(description = "역할설명")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "등록일시")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private LocalDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserRoleCreateDTO {
        @Schema(description = "역할명")
        private String name;
        
        @Schema(description = "역할코드")
        private String role;
        
        @Schema(description = "역할설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
    }

    @Data
    public static class UserRoleUpdateDTO {
        
        @Schema(description = "UserRole ID")
        @NotBlank(message = "ID는 필수 입력값입니다")
        private String id;
        
        @Schema(description = "역할명")
        private String name;
        
        @Schema(description = "역할코드")
        private String role;
        
        @Schema(description = "역할설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
    }

    @Data
    public static class UserRoleBatchUpdateDTO {
        @Schema(description = "UserRole ID 목록")
        private Set<String> ids;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserRoleDetailDTO {
        
        @Schema(description = "역할 ID")
        private String id;
        
        @Schema(description = "역할명")
        private String name;
        
        @Schema(description = "역할코드")
        private String role;
        
        @Schema(description = "역할설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime updatedAt;
    }

    @Data
    public static class UserRoleListDTO {
        
        @Schema(description = "역할 ID")
        private String id;
        
        @Schema(description = "역할명")
        private String name;
        
        @Schema(description = "역할코드")
        private String role;
        
        @Schema(description = "역할설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;
    }
} 