package dev.simplecore.simplix.demo.web.common.user.dto;

import java.time.LocalDateTime;
import java.util.Set;

import javax.validation.constraints.NotBlank;

import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.enums.OrganizationType;
import com.github.thkwag.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import static com.github.thkwag.searchable.core.condition.operator.SearchOperator.*;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:39:17.973+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserOrganizationDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserOrganizationSearchDTO {
        
        @Schema(description = "조직 ID")
        @SearchableField(operators = {EQUALS})
        private String id;
        
        @Schema(description = "조직명")
        @SearchableField(operators = {CONTAINS, EQUALS}, sortable = true)
        private String name;
        
        @Schema(description = "Parent")
        @SearchableField(entityField = "parent.id", operators = {EQUALS})
        private String parent;
        
        @Schema(description = "조직설명")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String description;
        
        @Schema(description = "순서")
        @SearchableField(operators = {EQUALS, GREATER_THAN, LESS_THAN})
        private Integer itemOrder;
        
        @Schema(description = "Children")
        @SearchableField(entityField = "children.id", operators = {EQUALS})
        private String children;
        
        @Schema(description = "등록일시")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private LocalDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserOrganizationCreateDTO {
        
        @Schema(description = "조직명")
        private String name;
        
        @Schema(description = "조직유형")
        private OrganizationType orgType;
        
        @Schema(description = "Parent")
        private String parent;
        
        @Schema(description = "조직설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "Children")
        private Set<String> children;
        
    }

    @Data
    public static class UserOrganizationUpdateDTO {
        
        @Schema(description = "UserOrganization ID")
        @NotBlank(message = "ID는 필수 입력값입니다")
        private String id;
        
        @Schema(description = "조직명")
        private String name;
        
        @Schema(description = "조직유형")
        private OrganizationType orgType;
        
        @Schema(description = "Parent")
        private String parent;
        
        @Schema(description = "조직설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "Children")
        private Set<String> children;
        
    }

    @Data
    public static class UserOrganizationBatchUpdateDTO {
        @Schema(description = "UserOrganization ID 목록")
        private Set<String> ids;
        
        @Schema(description = "조직유형")
        private OrganizationType orgType;
        
        @Schema(description = "Parent")
        private String parent;
        
        @Schema(description = "조직설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "Children")
        private Set<String> children;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserOrganizationDetailDTO {
        
        @Schema(description = "조직 ID")
        private String id;
        
        @Schema(description = "조직명")
        private String name;
        
        @Schema(description = "조직유형")
        private OrganizationType orgType;
        
        @Schema(description = "Parent")
        private UserOrganization parent;
        
        @Schema(description = "조직설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "Children")
        private Set<UserOrganization> children;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime updatedAt;
    }

    @Data
    public static class UserOrganizationListDTO {
        
        @Schema(description = "조직 ID")
        private String id;
        
        @Schema(description = "조직명")
        private String name;
        
        @Schema(description = "조직유형")
        private OrganizationType orgType;
        
        @Schema(description = "Parent")
        private UserOrganization parent;
        
        @Schema(description = "조직설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "Children")
        private Set<UserOrganization> children;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;
    }

    //----------------------------------
    // MyBatis DTO
    //----------------------------------

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class UserOrganizationTreeDTO {
        private String id;
        private String name;
        private OrganizationType orgType;
        private String parentId;
        private String description;
        private Integer itemOrder;
        private LocalDateTime createdAt;
        private String path;
        private Integer level;

        @Builder.Default
        private List<UserOrganizationTreeDTO> children = new ArrayList<>();
    }

    
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ParentOrgDTO {
        private String id;
        private String name;
        private OrganizationType orgType;
        private String description;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class UserOrganizationMyBatisDTO {
        private String id;
        private String name;
        private OrganizationType orgType;
        private String parentId;
        private String description;
        private Integer itemOrder;
        private LocalDateTime createdAt;
        private String path;
        private Integer level;
        private ParentOrgDTO parent;

        public UserOrganizationTreeDTO toTreeDTO() {
            return UserOrganizationTreeDTO.builder()
                    .id(id)
                    .name(name)
                    .orgType(orgType)
                    .parentId(parentId)
                    .description(description)
                    .itemOrder(itemOrder)
                    .createdAt(createdAt)
                    .path(path)
                    .level(level)
                    .children(new ArrayList<>())
                    .build();
        }
    }
} 