package dev.simplecore.simplix.demo.web.common.user.dto;

import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotBlank;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Set;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:39:03.028+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class UserPositionDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class UserPositionSearchDTO {
        
        @Schema(description = "직급 ID")
        @SearchableField(operators = {EQUALS})
        private String id;
        
        @Schema(description = "직급명")
        @SearchableField(operators = {CONTAINS, EQUALS}, sortable = true)
        private String name;
        
        @Schema(description = "직급설명")
        @SearchableField(operators = {CONTAINS})
        private String description;

        @Schema(description = "순서")
        @SearchableField(sortable = true)
        private Integer itemOrder;
        
        @Schema(description = "등록일시")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private OffsetDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class UserPositionCreateDTO {
        
        @Schema(description = "직급명")
        private String name;
        
        @Schema(description = "직급설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
    }

    
    @Data
    public static class UserPositionUpdateDTO {
        
        @Schema(description = "UserPosition ID")
        @NotBlank(message = "ID는 필수 입력값입니다")
        private String id;
        
        @Schema(description = "직급명")
        private String name;
        
        @Schema(description = "직급설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
    }

    @Data
    public static class UserPositionBatchUpdateDTO {
        @Schema(description = "UserPosition ID 목록")
        private Set<String> ids;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class UserPositionDetailDTO {
        
        @Schema(description = "직급 ID")
        private String id;
        
        @Schema(description = "직급명")
        private String name;
        
        @Schema(description = "직급설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class UserPositionListDTO {
        
        @Schema(description = "직급 ID")
        private String id;
        
        @Schema(description = "직급명")
        private String name;
        
        @Schema(description = "직급설명")
        private String description;
        
        @Schema(description = "순서")
        private Integer itemOrder;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;
    }
} 