package dev.simplecore.simplix.demo.web.common.auth.controller.rest;

import dev.simplecore.simplix.web.controller.SimpliXBaseController;
import dev.simplecore.simplix.web.controller.SimpliXStandardApi;
import dev.simplecore.simplix.core.model.SimpliXApiResponse;
import dev.simplecore.simplix.demo.web.common.auth.dto.AuthPermissionDTOs.*;
import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthPermission;
import dev.simplecore.simplix.demo.web.common.auth.service.AuthPermissionService;
import dev.simplecore.searchable.core.condition.SearchCondition;
import dev.simplecore.searchable.openapi.annotation.SearchableParams;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:04:09.015+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */

/**
 * 권한 설정 REST Controller
 *
 * @author thkwag
 * @since 2025-02-05
 */
@RestController
@RequestMapping("/api/auth/permission")
@Tag(name = "common.auth.AuthPermission", description = "권한 설정")
public class AuthPermissionRestController extends SimpliXBaseController<AuthPermission, String> {

    private final AuthPermissionService service;

    /**
     * Constructor for AuthPermissionRestController
     *
     * @param service The service instance for handling AuthPermission operations
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    protected AuthPermissionRestController(AuthPermissionService service) {
        super(service);
        this.service = service;
    }


    /**
     * Creates a new AuthPermission entity
     *
     * @param createDto The DTO containing the data to create a new AuthPermission
     * @return ResponseEntity containing the created AuthPermissionDetailDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @PostMapping("/create")
    @Operation(summary = "Create AuthPermission", description = "Creates a new 권한 설정")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<AuthPermissionDetailDTO>> create(@RequestBody @Validated AuthPermissionUpdateDTO createDto) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.create(createDto)));
    }
    

    /**
     * Updates an existing AuthPermission entity
     *
     * @param id The ID of the AuthPermission to update
     * @param updateDto The DTO containing the updated data
     * @return ResponseEntity containing the updated AuthPermissionDetailDTO or 404 if not found
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @PutMapping("/{id}")
    @Operation(summary = "Update AuthPermission", description = "Updates existing 권한 설정")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<AuthPermissionDetailDTO>> update(@PathVariable String id, @RequestBody @Validated AuthPermissionUpdateDTO updateDto) {
        return service.findById(id)
                .map(entity -> ResponseEntity.ok(SimpliXApiResponse.success(service.update(entity, updateDto))))
                .orElse(ResponseEntity.ok(SimpliXApiResponse.failure(null, "AuthPermission not found")));
    }


     /**
      * Updates multiple AuthPermission entities in a single operation
      *
      * @param updateDtos Set of DTOs containing the data to update multiple AuthPermission
      * @return ResponseEntity containing the list of updated AuthPermissionDetailDTOs and success status
      * @throws IllegalArgumentException if any of the updateDtos are invalid
      * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
      */
      @PatchMapping
      @Operation(summary = "Update Multiple AuthPermission", description = "Updates multiple existing 권한 설정s")
      @SimpliXStandardApi
      public ResponseEntity<SimpliXApiResponse<List<AuthPermissionDetailDTO>>> multiUpdate(@RequestBody Set<AuthPermissionUpdateDTO> updateDtos) {
          List<AuthPermissionDetailDTO> updatedItems = service.multiUpdate(updateDtos);
          return ResponseEntity.ok(SimpliXApiResponse.success(updatedItems));
      }


    /**
     * Deletes a AuthPermission by its ID
     *
     * @param id The ID of the AuthPermission to delete
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @DeleteMapping("/{id}")
    @Operation(summary = "Delete AuthPermission", description = "Deletes 권한 설정 by ID")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<Void>> delete(@PathVariable String id) {
        if (!service.existsById(id)) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "AuthPermission not found"));
        }
        service.delete(id);
        return ResponseEntity.ok(SimpliXApiResponse.success(null, "AuthPermission deleted successfully"));
    }


    /**
     * Retrieves a AuthPermission by its ID
     *
     * @param id The ID of the AuthPermission to retrieve
     * @return ResponseEntity containing the found AuthPermissionDetailDTO or 404 if not found
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/{id}")
    @Operation(summary = "Get AuthPermission", description = "Retrieves 권한 설정 by ID")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<AuthPermissionDetailDTO>> get(@PathVariable String id) {
        return service.findById(id, AuthPermissionDetailDTO.class)
                .map(result -> ResponseEntity.ok(SimpliXApiResponse.success(result)))
                .orElse(ResponseEntity.ok(SimpliXApiResponse.failure(null, "AuthPermission not found")));
    }


    /**
     * Batch updates multiple AuthPermission entities
     *
     * @param batchUpdateDto The DTO containing the batch update data
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @PatchMapping("/batch")
    @Operation(summary = "Batch Update AuthPermissions", description = "Updates multiple 권한 설정s")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<Void>> batchUpdate(@RequestBody @Validated AuthPermissionBatchUpdateDTO batchUpdateDto) {
        try {
            service.batchUpdate(batchUpdateDto);
            return ResponseEntity.ok(SimpliXApiResponse.success(null, "AuthPermissions updated successfully"));
        } catch (Exception e) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "Failed to process batch update"));
        }
    }

    /**
     * Deletes multiple AuthPermission entities by their IDs
     *
     * @param ids List of IDs of the AuthPermission entities to delete
     * @return ResponseEntity with success/failure message
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @DeleteMapping("/batch")
    @Operation(summary = "Delete multiple AuthPermissions", description = "Deletes multiple 권한 설정s by their IDs")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<Void>> batchDelete(@RequestParam List<String> ids) {
        try {
            service.batchDelete(ids);
            return ResponseEntity.ok(SimpliXApiResponse.success(null, "AuthPermissions deleted successfully"));
        } catch (Exception e) {
            return ResponseEntity.ok(SimpliXApiResponse.failure(null, "Failed to process batch delete"));
        }
    }


    //----------------------------------
    // Searchable JPA
    //----------------------------------

    /**
     * Search AuthPermission entities with GET method
     *
     * @param params Map of search parameters
     * @return ResponseEntity containing a page of AuthPermissionListDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @GetMapping("/search")
    @Operation(summary = "Search AuthPermission list (GET)", description = "Searches 권한 설정s with various conditions using GET method")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<Page<AuthPermissionListDTO>>> search(
        @RequestParam(required = false) @SearchableParams(AuthPermissionSearchDTO.class) Map<String, String> params
    ) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.search(params)));
    }

    /**
     * Search AuthPermission entities with POST method
     *
     * @param searchCondition The search conditions for filtering AuthPermissions
     * @return ResponseEntity containing a page of AuthPermissionListDTO
     * @generated SimpliX Generator Version 1.0.0 - 2025-02-05T14:04:09.015+09:00
     */
    @PostMapping("/search")
    @Operation(summary = "Search AuthPermission list (POST)", description = "Searches 권한 설정s with various conditions using POST method")
    @SimpliXStandardApi
    public ResponseEntity<SimpliXApiResponse<Page<AuthPermissionListDTO>>> search(
        @RequestBody @Validated SearchCondition<AuthPermissionSearchDTO> searchCondition
    ) {
        return ResponseEntity.ok(SimpliXApiResponse.success(service.search(searchCondition)));
    }
}
