package dev.simplecore.simplix.demo.web.common.auth.dto;

import dev.simplecore.searchable.core.annotation.SearchableField;
import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthPermission;
import dev.simplecore.simplix.demo.domain.common.auth.enums.PermissionTargetType;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccount;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.OffsetDateTime;
import java.util.Set;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T18:46:02.603+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class AuthRolePermissionDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class AuthRolePermissionSearchDTO {
        
        @Schema(description = "ID")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String id;
        
        @Schema(description = "Permission")
        @SearchableField(entityField = "permission.id", operators = {EQUALS}, sortable = true)
        private String permission;
        
        @Schema(description = "Permission Scope")
        @SearchableField(operators = {EQUALS}, sortable = true)
        private PermissionTargetType targetType;
        
        @Schema(description = "Role")
        @SearchableField(entityField = "role.id", operators = {EQUALS}, sortable = true)
        private String role;
        
        @Schema(description = "Organization")
        @SearchableField(entityField = "organization.id", operators = {EQUALS}, sortable = true)
        private String organization;
        
        @Schema(description = "User")
        @SearchableField(entityField = "userAccount.id", operators = {EQUALS}, sortable = true)
        private String userAccount;
        
        @Schema(description = "List View Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean listPermission;
        
        @Schema(description = "Detail View Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean viewPermission;
        
        @Schema(description = "Create Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean createPermission;
        
        @Schema(description = "Edit Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean editPermission;
        
        @Schema(description = "Delete Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean deletePermission;
        
        @Schema(description = "Extra Function 1 Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean extra1Permission;
        
        @Schema(description = "Extra Function 2 Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean extra2Permission;
        
        @Schema(description = "Extra Function 3 Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean extra3Permission;
        
        @Schema(description = "Extra Function 4 Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean extra4Permission;
        
        @Schema(description = "Extra Function 5 Permission")
        @SearchableField(operators = {EQUALS})
        private Boolean extra5Permission;
        
        @Schema(description = "Description")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "Registered Date Time")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private OffsetDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class AuthRolePermissionUpdateDTO {
        
        @Schema(description = "AuthRolePermission ID")
        private String id;
        
        @Schema(description = "Permission")
        private String permission;
        
        @Schema(description = "Permission Scope")
        private PermissionTargetType targetType;
        
        @Schema(description = "Role")
        private String role;
        
        @Schema(description = "Organization")
        private String organization;
        
        @Schema(description = "User")
        private String userAccount;
        
        @Schema(description = "List View Permission")
        private Boolean listPermission;
        
        @Schema(description = "Detail View Permission")
        private Boolean viewPermission;
        
        @Schema(description = "Create Permission")
        private Boolean createPermission;
        
        @Schema(description = "Edit Permission")
        private Boolean editPermission;
        
        @Schema(description = "Delete Permission")
        private Boolean deletePermission;
        
        @Schema(description = "Extra Function 1 Permission")
        private Boolean extra1Permission;
        
        @Schema(description = "Extra Function 2 Permission")
        private Boolean extra2Permission;
        
        @Schema(description = "Extra Function 3 Permission")
        private Boolean extra3Permission;
        
        @Schema(description = "Extra Function 4 Permission")
        private Boolean extra4Permission;
        
        @Schema(description = "Extra Function 5 Permission")
        private Boolean extra5Permission;
        
        @Schema(description = "Description")
        private String description;
        
    }

    @Data
    public static class AuthRolePermissionBatchUpdateDTO {
        @Schema(description = "AuthRolePermission ID List")
        private Set<String> ids;
        
        @Schema(description = "List View Permission")
        private Boolean listPermission;
        
        @Schema(description = "Detail View Permission")
        private Boolean viewPermission;
        
        @Schema(description = "Create Permission")
        private Boolean createPermission;
        
        @Schema(description = "Edit Permission")
        private Boolean editPermission;
        
        @Schema(description = "Delete Permission")
        private Boolean deletePermission;
        
        @Schema(description = "Extra Function 1 Permission")
        private Boolean extra1Permission;
        
        @Schema(description = "Extra Function 2 Permission")
        private Boolean extra2Permission;
        
        @Schema(description = "Extra Function 3 Permission")
        private Boolean extra3Permission;
        
        @Schema(description = "Extra Function 4 Permission")
        private Boolean extra4Permission;
        
        @Schema(description = "Extra Function 5 Permission")
        private Boolean extra5Permission;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class AuthRolePermissionDetailDTO {
        
        @Schema(description = "ID")
        private String id;
        
        @Schema(description = "Permission")
        private AuthPermission permission;
        
        @Schema(description = "Permission Scope")
        private PermissionTargetType targetType;
        
        @Schema(description = "Role")
        private UserRole role;
        
        @Schema(description = "Organization")
        private UserOrganization organization;
        
        @Schema(description = "User")
        private UserAccount userAccount;
        
        @Schema(description = "List View Permission")
        private Boolean listPermission;
        
        @Schema(description = "Detail View Permission")
        private Boolean viewPermission;
        
        @Schema(description = "Create Permission")
        private Boolean createPermission;
        
        @Schema(description = "Edit Permission")
        private Boolean editPermission;
        
        @Schema(description = "Delete Permission")
        private Boolean deletePermission;
        
        @Schema(description = "Extra Function 1 Permission")
        private Boolean extra1Permission;
        
        @Schema(description = "Extra Function 2 Permission")
        private Boolean extra2Permission;
        
        @Schema(description = "Extra Function 3 Permission")
        private Boolean extra3Permission;
        
        @Schema(description = "Extra Function 4 Permission")
        private Boolean extra4Permission;
        
        @Schema(description = "Extra Function 5 Permission")
        private Boolean extra5Permission;
        
        @Schema(description = "Description")
        private String description;
        
        @Schema(description = "Created By")
        private String createdBy;

        @Schema(description = "Registered Date Time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated By")
        private String updatedBy;

        @Schema(description = "Updated Date Time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class AuthRolePermissionListDTO {
        
        @Schema(description = "ID")
        private String id;
        
        @Schema(description = "Permission")
        private AuthPermission permission;
        
        @Schema(description = "Permission Scope")
        private PermissionTargetType targetType;
        
        @Schema(description = "Role")
        private UserRole role;
        
        @Schema(description = "Organization")
        private UserOrganization organization;
        
        @Schema(description = "User")
        private UserAccount userAccount;
        
        @Schema(description = "List View Permission")
        private Boolean listPermission;
        
        @Schema(description = "Detail View Permission")
        private Boolean viewPermission;
        
        @Schema(description = "Create Permission")
        private Boolean createPermission;
        
        @Schema(description = "Edit Permission")
        private Boolean editPermission;
        
        @Schema(description = "Delete Permission")
        private Boolean deletePermission;
        
        @Schema(description = "Extra Function 1 Permission")
        private Boolean extra1Permission;
        
        @Schema(description = "Extra Function 2 Permission")
        private Boolean extra2Permission;
        
        @Schema(description = "Extra Function 3 Permission")
        private Boolean extra3Permission;
        
        @Schema(description = "Extra Function 4 Permission")
        private Boolean extra4Permission;
        
        @Schema(description = "Extra Function 5 Permission")
        private Boolean extra5Permission;
        
        @Schema(description = "Description")
        private String description;
        
        @Schema(description = "Registered Date Time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;
    }
} 