package dev.simplecore.simplix.demo.web.common.auth.dto;

import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.OffsetDateTime;
import java.util.Set;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:04:09.015+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class AuthPermissionDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class AuthPermissionSearchDTO {
        
        @Schema(description = "Permission ID")
        @SearchableField(operators = {EQUALS})
        private String id;
        
        @Schema(description = "Permission Code")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String name;
        
        @Schema(description = "Permission Description")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "Whether to use the list view function")
        @SearchableField(operators = {EQUALS})
        private Boolean useList;
        
        @Schema(description = "Whether to use the detail view function")
        @SearchableField(operators = {EQUALS})
        private Boolean useView;
        
        @Schema(description = "Whether to use the create function")
        @SearchableField(operators = {EQUALS})
        private Boolean useCreate;
        
        @Schema(description = "Whether to use the edit function")
        @SearchableField(operators = {EQUALS})
        private Boolean useEdit;
        
        @Schema(description = "Whether to use the delete function")
        @SearchableField(operators = {EQUALS})
        private Boolean useDelete;
        
        @Schema(description = "Whether to use extra function 1")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra1;
        
        @Schema(description = "Whether to use extra function 2")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra2;
        
        @Schema(description = "Whether to use extra function 3")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra3;
        
        @Schema(description = "Whether to use extra function 4")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra4;
        
        @Schema(description = "Whether to use extra function 5")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra5;
        
        @Schema(description = "Extra Function 1 Name")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra1Name;
        
        @Schema(description = "Extra Function 2 Name")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra2Name;
        
        @Schema(description = "Extra Function 3 Name")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra3Name;
        
        @Schema(description = "Extra Function 4 Name")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra4Name;
        
        @Schema(description = "Extra Function 5 Name")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra5Name;
        
        @Schema(description = "Registration date and time")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private OffsetDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class AuthPermissionUpdateDTO {
        
        @Schema(description = "AuthPermission ID")
        private String id;
        
        @Schema(description = "Permission Code")
        private String name;
        
        @Schema(description = "Permission Description")
        private String description;
        
        @Schema(description = "Whether to use the list view function")
        private Boolean useList;
        
        @Schema(description = "Whether to use the detail view function")
        private Boolean useView;
        
        @Schema(description = "Whether to use the create function")
        private Boolean useCreate;
        
        @Schema(description = "Whether to use the edit function")
        private Boolean useEdit;
        
        @Schema(description = "Whether to use the delete function")
        private Boolean useDelete;
        
        @Schema(description = "Whether to use extra function 1")
        private Boolean useExtra1;
        
        @Schema(description = "Whether to use extra function 2")
        private Boolean useExtra2;
        
        @Schema(description = "Whether to use extra function 3")
        private Boolean useExtra3;
        
        @Schema(description = "Whether to use extra function 4")
        private Boolean useExtra4;
        
        @Schema(description = "Whether to use extra function 5")
        private Boolean useExtra5;
        
        @Schema(description = "Extra Function 1 Name")
        private String extra1Name;
        
        @Schema(description = "Extra Function 2 Name")
        private String extra2Name;
        
        @Schema(description = "Extra Function 3 Name")
        private String extra3Name;
        
        @Schema(description = "Extra Function 4 Name")
        private String extra4Name;
        
        @Schema(description = "Extra Function 5 Name")
        private String extra5Name;
        
    }

    @Data
    public static class AuthPermissionBatchUpdateDTO {
        @Schema(description = "AuthPermission ID List")
        private Set<String> ids;
        
        @Schema(description = "Whether to use the list view function")
        private Boolean useList;
        
        @Schema(description = "Whether to use the detail view function")
        private Boolean useView;
        
        @Schema(description = "Whether to use the create function")
        private Boolean useCreate;
        
        @Schema(description = "Whether to use the edit function")
        private Boolean useEdit;
        
        @Schema(description = "Whether to use the delete function")
        private Boolean useDelete;
        
        @Schema(description = "Whether to use extra function 1")
        private Boolean useExtra1;
        
        @Schema(description = "Whether to use extra function 2")
        private Boolean useExtra2;
        
        @Schema(description = "Whether to use extra function 3")
        private Boolean useExtra3;
        
        @Schema(description = "Whether to use extra function 4")
        private Boolean useExtra4;
        
        @Schema(description = "Whether to use extra function 5")
        private Boolean useExtra5;
        
        @Schema(description = "Extra Function 1 Name")
        private String extra1Name;
        
        @Schema(description = "Extra Function 2 Name")
        private String extra2Name;
        
        @Schema(description = "Extra Function 3 Name")
        private String extra3Name;
        
        @Schema(description = "Extra Function 4 Name")
        private String extra4Name;
        
        @Schema(description = "Extra Function 5 Name")
        private String extra5Name;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class AuthPermissionDetailDTO {
        
        @Schema(description = "Permission ID")
        private String id;
        
        @Schema(description = "Permission Code")
        private String name;
        
        @Schema(description = "Permission Description")
        private String description;
        
        @Schema(description = "Whether to use the list view function")
        private Boolean useList;
        
        @Schema(description = "Whether to use the detail view function")
        private Boolean useView;
        
        @Schema(description = "Whether to use the create function")
        private Boolean useCreate;
        
        @Schema(description = "Whether to use the edit function")
        private Boolean useEdit;
        
        @Schema(description = "Whether to use the delete function")
        private Boolean useDelete;
        
        @Schema(description = "Whether to use extra function 1")
        private Boolean useExtra1;
        
        @Schema(description = "Whether to use extra function 2")
        private Boolean useExtra2;
        
        @Schema(description = "Whether to use extra function 3")
        private Boolean useExtra3;
        
        @Schema(description = "Whether to use extra function 4")
        private Boolean useExtra4;
        
        @Schema(description = "Whether to use extra function 5")
        private Boolean useExtra5;
        
        @Schema(description = "Extra Function 1 Name")
        private String extra1Name;
        
        @Schema(description = "Extra Function 2 Name")
        private String extra2Name;
        
        @Schema(description = "Extra Function 3 Name")
        private String extra3Name;
        
        @Schema(description = "Extra Function 4 Name")
        private String extra4Name;
        
        @Schema(description = "Extra Function 5 Name")
        private String extra5Name;
        
        @Schema(description = "Created By")
        private String createdBy;

        @Schema(description = "Registration date and time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated By")
        private String updatedBy;

        @Schema(description = "Updated date and time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class AuthPermissionListDTO {
        
        @Schema(description = "Permission ID")
        private String id;
        
        @Schema(description = "Permission Code")
        private String name;
        
        @Schema(description = "Permission Description")
        private String description;
        
        @Schema(description = "Whether to use the list view function")
        private Boolean useList;
        
        @Schema(description = "Whether to use the detail view function")
        private Boolean useView;
        
        @Schema(description = "Whether to use the create function")
        private Boolean useCreate;
        
        @Schema(description = "Whether to use the edit function")
        private Boolean useEdit;
        
        @Schema(description = "Whether to use the delete function")
        private Boolean useDelete;
        
        @Schema(description = "Whether to use extra function 1")
        private Boolean useExtra1;
        
        @Schema(description = "Whether to use extra function 2")
        private Boolean useExtra2;
        
        @Schema(description = "Whether to use extra function 3")
        private Boolean useExtra3;
        
        @Schema(description = "Whether to use extra function 4")
        private Boolean useExtra4;
        
        @Schema(description = "Whether to use extra function 5")
        private Boolean useExtra5;
        
        @Schema(description = "Extra Function 1 Name")
        private String extra1Name;
        
        @Schema(description = "Extra Function 2 Name")
        private String extra2Name;
        
        @Schema(description = "Extra Function 3 Name")
        private String extra3Name;
        
        @Schema(description = "Extra Function 4 Name")
        private String extra4Name;
        
        @Schema(description = "Extra Function 5 Name")
        private String extra5Name;
        
        @Schema(description = "Registration date and time")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;
    }
} 