package dev.simplecore.simplix.demo.web.common.auth.dto;

import java.time.LocalDateTime;
import java.util.Set;

import dev.simplecore.simplix.demo.domain.common.auth.entity.AuthPermission;
import dev.simplecore.simplix.demo.domain.common.auth.enums.PermissionTargetType;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserAccount;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserOrganization;
import dev.simplecore.simplix.demo.domain.common.user.entity.UserRole;
import com.github.thkwag.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import static com.github.thkwag.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T18:46:02.603+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class AuthRolePermissionDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class AuthRolePermissionSearchDTO {
        
        @Schema(description = "ID")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String id;
        
        @Schema(description = "권한")
        @SearchableField(entityField = "permission.id", operators = {EQUALS}, sortable = true)
        private String permission;
        
        @Schema(description = "권한 범위")
        @SearchableField(operators = {EQUALS}, sortable = true)
        private PermissionTargetType targetType;
        
        @Schema(description = "역할")
        @SearchableField(entityField = "role.id", operators = {EQUALS}, sortable = true)
        private String role;
        
        @Schema(description = "조직")
        @SearchableField(entityField = "organization.id", operators = {EQUALS}, sortable = true)
        private String organization;
        
        @Schema(description = "사용자")
        @SearchableField(entityField = "userAccount.id", operators = {EQUALS}, sortable = true)
        private String userAccount;
        
        @Schema(description = "목록 조회 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean listPermission;
        
        @Schema(description = "상세 조회 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean viewPermission;
        
        @Schema(description = "생성 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean createPermission;
        
        @Schema(description = "수정 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean editPermission;
        
        @Schema(description = "삭제 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean deletePermission;
        
        @Schema(description = "추가 기능 1 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean extra1Permission;
        
        @Schema(description = "추가 기능 2 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean extra2Permission;
        
        @Schema(description = "추가 기능 3 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean extra3Permission;
        
        @Schema(description = "추가 기능 4 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean extra4Permission;
        
        @Schema(description = "추가 기능 5 권한")
        @SearchableField(operators = {EQUALS})
        private Boolean extra5Permission;
        
        @Schema(description = "설명")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "등록일시")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private LocalDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class AuthRolePermissionUpdateDTO {
        
        @Schema(description = "AuthRolePermission ID")
        private String id;
        
        @Schema(description = "권한")
        private String permission;
        
        @Schema(description = "권한 범위")
        private PermissionTargetType targetType;
        
        @Schema(description = "역할")
        private String role;
        
        @Schema(description = "조직")
        private String organization;
        
        @Schema(description = "사용자")
        private String userAccount;
        
        @Schema(description = "목록 조회 권한")
        private Boolean listPermission;
        
        @Schema(description = "상세 조회 권한")
        private Boolean viewPermission;
        
        @Schema(description = "생성 권한")
        private Boolean createPermission;
        
        @Schema(description = "수정 권한")
        private Boolean editPermission;
        
        @Schema(description = "삭제 권한")
        private Boolean deletePermission;
        
        @Schema(description = "추가 기능 1 권한")
        private Boolean extra1Permission;
        
        @Schema(description = "추가 기능 2 권한")
        private Boolean extra2Permission;
        
        @Schema(description = "추가 기능 3 권한")
        private Boolean extra3Permission;
        
        @Schema(description = "추가 기능 4 권한")
        private Boolean extra4Permission;
        
        @Schema(description = "추가 기능 5 권한")
        private Boolean extra5Permission;
        
        @Schema(description = "설명")
        private String description;
        
    }

    @Data
    public static class AuthRolePermissionBatchUpdateDTO {
        @Schema(description = "AuthRolePermission ID 목록")
        private Set<String> ids;
        
        @Schema(description = "목록 조회 권한")
        private Boolean listPermission;
        
        @Schema(description = "상세 조회 권한")
        private Boolean viewPermission;
        
        @Schema(description = "생성 권한")
        private Boolean createPermission;
        
        @Schema(description = "수정 권한")
        private Boolean editPermission;
        
        @Schema(description = "삭제 권한")
        private Boolean deletePermission;
        
        @Schema(description = "추가 기능 1 권한")
        private Boolean extra1Permission;
        
        @Schema(description = "추가 기능 2 권한")
        private Boolean extra2Permission;
        
        @Schema(description = "추가 기능 3 권한")
        private Boolean extra3Permission;
        
        @Schema(description = "추가 기능 4 권한")
        private Boolean extra4Permission;
        
        @Schema(description = "추가 기능 5 권한")
        private Boolean extra5Permission;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class AuthRolePermissionDetailDTO {
        
        @Schema(description = "ID")
        private String id;
        
        @Schema(description = "권한")
        private AuthPermission permission;
        
        @Schema(description = "권한 범위")
        private PermissionTargetType targetType;
        
        @Schema(description = "역할")
        private UserRole role;
        
        @Schema(description = "조직")
        private UserOrganization organization;
        
        @Schema(description = "사용자")
        private UserAccount userAccount;
        
        @Schema(description = "목록 조회 권한")
        private Boolean listPermission;
        
        @Schema(description = "상세 조회 권한")
        private Boolean viewPermission;
        
        @Schema(description = "생성 권한")
        private Boolean createPermission;
        
        @Schema(description = "수정 권한")
        private Boolean editPermission;
        
        @Schema(description = "삭제 권한")
        private Boolean deletePermission;
        
        @Schema(description = "추가 기능 1 권한")
        private Boolean extra1Permission;
        
        @Schema(description = "추가 기능 2 권한")
        private Boolean extra2Permission;
        
        @Schema(description = "추가 기능 3 권한")
        private Boolean extra3Permission;
        
        @Schema(description = "추가 기능 4 권한")
        private Boolean extra4Permission;
        
        @Schema(description = "추가 기능 5 권한")
        private Boolean extra5Permission;
        
        @Schema(description = "설명")
        private String description;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime updatedAt;
    }

    @Data
    public static class AuthRolePermissionListDTO {
        
        @Schema(description = "ID")
        private String id;
        
        @Schema(description = "권한")
        private AuthPermission permission;
        
        @Schema(description = "권한 범위")
        private PermissionTargetType targetType;
        
        @Schema(description = "역할")
        private UserRole role;
        
        @Schema(description = "조직")
        private UserOrganization organization;
        
        @Schema(description = "사용자")
        private UserAccount userAccount;
        
        @Schema(description = "목록 조회 권한")
        private Boolean listPermission;
        
        @Schema(description = "상세 조회 권한")
        private Boolean viewPermission;
        
        @Schema(description = "생성 권한")
        private Boolean createPermission;
        
        @Schema(description = "수정 권한")
        private Boolean editPermission;
        
        @Schema(description = "삭제 권한")
        private Boolean deletePermission;
        
        @Schema(description = "추가 기능 1 권한")
        private Boolean extra1Permission;
        
        @Schema(description = "추가 기능 2 권한")
        private Boolean extra2Permission;
        
        @Schema(description = "추가 기능 3 권한")
        private Boolean extra3Permission;
        
        @Schema(description = "추가 기능 4 권한")
        private Boolean extra4Permission;
        
        @Schema(description = "추가 기능 5 권한")
        private Boolean extra5Permission;
        
        @Schema(description = "설명")
        private String description;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;
    }
} 