package dev.simplecore.simplix.demo.web.common.auth.dto;
import java.time.LocalDateTime;
import java.util.Set;
import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-02-05T14:04:09.015+09:00
 * Generated By: thkwag<thkwag@gmail.com>
 */
public class AuthPermissionDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class AuthPermissionSearchDTO {
        
        @Schema(description = "권한 ID")
        @SearchableField(operators = {EQUALS})
        private String id;
        
        @Schema(description = "권한코드")
        @SearchableField(operators = {EQUALS, CONTAINS}, sortable = true)
        private String name;
        
        @Schema(description = "권한설명")
        @SearchableField(operators = {CONTAINS})
        private String description;
        
        @Schema(description = "목록 조회 기능 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useList;
        
        @Schema(description = "상세 조회 기능 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useView;
        
        @Schema(description = "생성 기능 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useCreate;
        
        @Schema(description = "수정 기능 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useEdit;
        
        @Schema(description = "삭제 기능 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useDelete;
        
        @Schema(description = "추가 기능 1 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra1;
        
        @Schema(description = "추가 기능 2 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra2;
        
        @Schema(description = "추가 기능 3 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra3;
        
        @Schema(description = "추가 기능 4 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra4;
        
        @Schema(description = "추가 기능 5 사용 여부")
        @SearchableField(operators = {EQUALS})
        private Boolean useExtra5;
        
        @Schema(description = "추가 기능 1 이름")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra1Name;
        
        @Schema(description = "추가 기능 2 이름")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra2Name;
        
        @Schema(description = "추가 기능 3 이름")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra3Name;
        
        @Schema(description = "추가 기능 4 이름")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra4Name;
        
        @Schema(description = "추가 기능 5 이름")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String extra5Name;
        
        @Schema(description = "등록일시")
        @SearchableField(operators = {GREATER_THAN, LESS_THAN, BETWEEN}, sortable = true)
        private LocalDateTime createdAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class AuthPermissionUpdateDTO {
        
        @Schema(description = "AuthPermission ID")
        private String id;
        
        @Schema(description = "권한코드")
        private String name;
        
        @Schema(description = "권한설명")
        private String description;
        
        @Schema(description = "목록 조회 기능 사용 여부")
        private Boolean useList;
        
        @Schema(description = "상세 조회 기능 사용 여부")
        private Boolean useView;
        
        @Schema(description = "생성 기능 사용 여부")
        private Boolean useCreate;
        
        @Schema(description = "수정 기능 사용 여부")
        private Boolean useEdit;
        
        @Schema(description = "삭제 기능 사용 여부")
        private Boolean useDelete;
        
        @Schema(description = "추가 기능 1 사용 여부")
        private Boolean useExtra1;
        
        @Schema(description = "추가 기능 2 사용 여부")
        private Boolean useExtra2;
        
        @Schema(description = "추가 기능 3 사용 여부")
        private Boolean useExtra3;
        
        @Schema(description = "추가 기능 4 사용 여부")
        private Boolean useExtra4;
        
        @Schema(description = "추가 기능 5 사용 여부")
        private Boolean useExtra5;
        
        @Schema(description = "추가 기능 1 이름")
        private String extra1Name;
        
        @Schema(description = "추가 기능 2 이름")
        private String extra2Name;
        
        @Schema(description = "추가 기능 3 이름")
        private String extra3Name;
        
        @Schema(description = "추가 기능 4 이름")
        private String extra4Name;
        
        @Schema(description = "추가 기능 5 이름")
        private String extra5Name;
        
    }

    @Data
    public static class AuthPermissionBatchUpdateDTO {
        @Schema(description = "AuthPermission ID 목록")
        private Set<String> ids;
        
        @Schema(description = "목록 조회 기능 사용 여부")
        private Boolean useList;
        
        @Schema(description = "상세 조회 기능 사용 여부")
        private Boolean useView;
        
        @Schema(description = "생성 기능 사용 여부")
        private Boolean useCreate;
        
        @Schema(description = "수정 기능 사용 여부")
        private Boolean useEdit;
        
        @Schema(description = "삭제 기능 사용 여부")
        private Boolean useDelete;
        
        @Schema(description = "추가 기능 1 사용 여부")
        private Boolean useExtra1;
        
        @Schema(description = "추가 기능 2 사용 여부")
        private Boolean useExtra2;
        
        @Schema(description = "추가 기능 3 사용 여부")
        private Boolean useExtra3;
        
        @Schema(description = "추가 기능 4 사용 여부")
        private Boolean useExtra4;
        
        @Schema(description = "추가 기능 5 사용 여부")
        private Boolean useExtra5;
        
        @Schema(description = "추가 기능 1 이름")
        private String extra1Name;
        
        @Schema(description = "추가 기능 2 이름")
        private String extra2Name;
        
        @Schema(description = "추가 기능 3 이름")
        private String extra3Name;
        
        @Schema(description = "추가 기능 4 이름")
        private String extra4Name;
        
        @Schema(description = "추가 기능 5 이름")
        private String extra5Name;
        
    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class AuthPermissionDetailDTO {
        
        @Schema(description = "권한 ID")
        private String id;
        
        @Schema(description = "권한코드")
        private String name;
        
        @Schema(description = "권한설명")
        private String description;
        
        @Schema(description = "목록 조회 기능 사용 여부")
        private Boolean useList;
        
        @Schema(description = "상세 조회 기능 사용 여부")
        private Boolean useView;
        
        @Schema(description = "생성 기능 사용 여부")
        private Boolean useCreate;
        
        @Schema(description = "수정 기능 사용 여부")
        private Boolean useEdit;
        
        @Schema(description = "삭제 기능 사용 여부")
        private Boolean useDelete;
        
        @Schema(description = "추가 기능 1 사용 여부")
        private Boolean useExtra1;
        
        @Schema(description = "추가 기능 2 사용 여부")
        private Boolean useExtra2;
        
        @Schema(description = "추가 기능 3 사용 여부")
        private Boolean useExtra3;
        
        @Schema(description = "추가 기능 4 사용 여부")
        private Boolean useExtra4;
        
        @Schema(description = "추가 기능 5 사용 여부")
        private Boolean useExtra5;
        
        @Schema(description = "추가 기능 1 이름")
        private String extra1Name;
        
        @Schema(description = "추가 기능 2 이름")
        private String extra2Name;
        
        @Schema(description = "추가 기능 3 이름")
        private String extra3Name;
        
        @Schema(description = "추가 기능 4 이름")
        private String extra4Name;
        
        @Schema(description = "추가 기능 5 이름")
        private String extra5Name;
        
        @Schema(description = "등록자")
        private String createdBy;

        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;

        @Schema(description = "수정자")
        private String updatedBy;

        @Schema(description = "수정일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime updatedAt;
    }

    @Data
    public static class AuthPermissionListDTO {
        
        @Schema(description = "권한 ID")
        private String id;
        
        @Schema(description = "권한코드")
        private String name;
        
        @Schema(description = "권한설명")
        private String description;
        
        @Schema(description = "목록 조회 기능 사용 여부")
        private Boolean useList;
        
        @Schema(description = "상세 조회 기능 사용 여부")
        private Boolean useView;
        
        @Schema(description = "생성 기능 사용 여부")
        private Boolean useCreate;
        
        @Schema(description = "수정 기능 사용 여부")
        private Boolean useEdit;
        
        @Schema(description = "삭제 기능 사용 여부")
        private Boolean useDelete;
        
        @Schema(description = "추가 기능 1 사용 여부")
        private Boolean useExtra1;
        
        @Schema(description = "추가 기능 2 사용 여부")
        private Boolean useExtra2;
        
        @Schema(description = "추가 기능 3 사용 여부")
        private Boolean useExtra3;
        
        @Schema(description = "추가 기능 4 사용 여부")
        private Boolean useExtra4;
        
        @Schema(description = "추가 기능 5 사용 여부")
        private Boolean useExtra5;
        
        @Schema(description = "추가 기능 1 이름")
        private String extra1Name;
        
        @Schema(description = "추가 기능 2 이름")
        private String extra2Name;
        
        @Schema(description = "추가 기능 3 이름")
        private String extra3Name;
        
        @Schema(description = "추가 기능 4 이름")
        private String extra4Name;
        
        @Schema(description = "추가 기능 5 이름")
        private String extra5Name;
        
        @Schema(description = "등록일시")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private LocalDateTime createdAt;
    }
} 