package dev.simplecore.simplix.demo.web.common.code.dto;

import dev.simplecore.simplix.demo.domain.common.code.entity.CodeGroup;
import java.util.*;
import java.time.*;
import dev.simplecore.searchable.core.annotation.SearchableField;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.*;

import static dev.simplecore.searchable.core.condition.operator.SearchOperator.*;

/**
 * This file was auto-generated by SimpliX Generator
 * 
 * Generator Version: 0.0.1
 * Generated At: 2025-07-17T00:33:22.394+09:00
 * Generated By: Taehwan Kwag<thkwag@gmail.com>
 */
public class CodeGroupDTOs {

    //----------------------------------
    // Search
    //----------------------------------

    @Getter
    @Setter
    public static class CodeGroupSearchDTO {
        
        @Schema(description = "Code ID")
        @SearchableField(operators = {EQUALS})
        private String codeGroupId;

        @Schema(description = "Group Key")
        @SearchableField(operators = {EQUALS}, sortable = true)
        private String groupKey;
            
        @Schema(description = "Group Name")
        @SearchableField(operators = {EQUALS, CONTAINS})
        private String groupName;
            

        @Schema(description = "Sort Order")
        @SearchableField(sortable = true)
        private Integer sortOrder;

        @Schema(description = "Is Active")
        @SearchableField(operators = {EQUALS})
        private Boolean isActive;
            
        @Schema(description = "Parent ID")
        @SearchableField(operators = {EQUALS})
        private String parentId;

        //----------

        @Schema(description = "Created by")
        private String createdBy;

        @Schema(description = "Created at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated by")
        private String updatedBy;

        @Schema(description = "Updated at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    //----------------------------------
    // Create, Update
    //----------------------------------

    @Data
    public static class CodeGroupCreateDTO {

        @Schema(description = "Group Key")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 50, message = "{validation.range.length}")
        @Pattern(regexp = "^[A-Z0-9_]+$", message = "{validation.groupKey.pattern}")
        private String groupKey;

        @Schema(description = "Group Name")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 100, message = "{validation.range.length}")
        private String groupName;

        @Schema(description = "[i18n] Group Name")
        private Map<String, String> groupNameI18n;

        @Schema(description = "Description")
        @NotBlank(message = "{validation.required}")
        @Length(max = 500, message = "{validation.max.length}")
        private String description;

        @Schema(description = "[i18n] Description")
        private Map<String, String>  descriptionI18n;

        @Schema(description = "Sort Order")
        @Min(value = 0, message = "{validation.min.value}")
        @Max(value = 9999, message = "{validation.max.value}")
        private Integer sortOrder;

        @Schema(description = "Is Active")
        @NotNull(message = "{validation.required}")
        private Boolean isActive;

        @Schema(description = "Parent ID")
        @Length(max = 50, message = "{validation.max.length}")
        private String parentId;
        
    }

    @Data
    public static class CodeGroupUpdateDTO {
        
        @Schema(description = "Code ID")
        @NotBlank(message = "{validation.required}")
        private String codeGroupId;

        @Schema(description = "Group Key")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 50, message = "{validation.range.length}")
        @Pattern(regexp = "^[A-Z0-9_]+$", message = "{validation.groupKey.pattern}")
        private String groupKey;

        @Schema(description = "Group Name")
        @NotBlank(message = "{validation.required}")
        @Length(min = 1, max = 100, message = "{validation.range.length}")
        private String groupName;

        @Schema(description = "[i18n] Group Name")
        private Map<String, String> groupNameI18n;

        @Schema(description = "Description")
        @NotBlank(message = "{validation.required}")
        @Length(max = 500, message = "{validation.max.length}")
        private String description;

        @Schema(description = "[i18n] Description")
        private Map<String, String>  descriptionI18n;

        @Schema(description = "Sort Order")
        @Min(value = 0, message = "{validation.min.value}")
        @Max(value = 999999, message = "{validation.max.value}")
        private Integer sortOrder;

        @Schema(description = "Is Active")
        @NotNull(message = "{validation.required}")
        private Boolean isActive;

        @Schema(description = "Parent ID")
        @Length(max = 50, message = "{validation.max.length}")
        private String parentId;
    }

    @Data
    public static class CodeGroupBatchUpdateDTO {

        @Schema(description = "Code ID list")
        @NotEmpty(message = "{validation.required}")
        @Size(min = 1, max = 100, message = "{validation.range.size}")
        private Set<String> codeGroupIds;

        @Schema(description = "Is Active")
        private Boolean isActive;
    }

    @Data
    public static class CodeGroupOrderUpdateDTO {
        @Schema(description = "Code ID")
        @NotBlank(message = "ID is a required input value")
        private String codeGroupId;

        @Schema(description = "Sort Order")
        private Integer sortOrder;

    }

    //----------------------------------
    // Projection
    //----------------------------------

    @Data
    public static class CodeGroupDetailDTO {
        
        @Schema(description = "Code ID")
        private String codeGroupId;
        
        @Schema(description = "Group Key")
        private String groupKey;

        @Schema(description = "Group Name")
        private String groupName;

        @Schema(description = "[i18n] Group Name")
        private Map<String, String> groupNameI18n;

        @Schema(description = "Description")
        private String description;

        @Schema(description = "[i18n] Description")
        private Map<String, String>  descriptionI18n;
        
        @Schema(description = "Sort Order")
        private Integer sortOrder;

        @Schema(description = "Is Active")
        private Boolean isActive;
        
        @Schema(description = "Parent ID")
        private String parentId;

        @Schema(description = "Parent Group")
        private CodeGroup parentGroup;

        @Schema(description = "Children")
        private List<CodeGroup> children;

        //----------

        @Schema(description = "Created by")
        private String createdBy;

        @Schema(description = "Created at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated by")
        private String updatedBy;

        @Schema(description = "Updated at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }

    @Data
    public static class CodeGroupListDTO {

        @Schema(description = "Code ID")
        private String codeGroupId;

        @Schema(description = "Group Key")
        private String groupKey;

        @Schema(description = "Group Name")
        private String groupName;

        @Schema(description = "[i18n] Group Name")
        private Map<String, String> groupNameI18n;

        @Schema(description = "Description")
        private String description;

        @Schema(description = "[i18n] Description")
        private Map<String, String>  descriptionI18n;

        @Schema(description = "Sort Order")
        private Integer sortOrder;

        @Schema(description = "Is Active")
        private Boolean isActive;

        @Schema(description = "Parent ID")
        private String parentId;

        @Schema(description = "Parent Group")
        private CodeGroup parentGroup;

        @Schema(description = "Children")
        private List<CodeGroup> children;

        //----------
        
        @Schema(description = "Created by")
        private String createdBy;

        @Schema(description = "Created at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime createdAt;

        @Schema(description = "Updated by")
        private String updatedBy;

        @Schema(description = "Updated at")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
        private OffsetDateTime updatedAt;
    }
} 